amazon-braket/amazon-braket-sdk-python

setup.py
=> infra: Use public PyPi dependency

README.md
=> documentation: README update

src/braket/_sdk/_version.py
The only way to update a description in PyPi is to upload new files;
however, uploading an existing version is prohibited. The recommended
way to deal with this is with
[post-releases](https://www.python.org/dev/peps/pep-0440/#post-releases).
=> fix: Post-release 1.0.0.post1

README.md
=> documentation: add readthedocs link to README

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation_request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/stale_issue.yml
* add github action for closing stale issues
=> infra: add github action for stale issues

src/braket/_sdk/_version.py
* update version to release changes in SDK
* needed for AwsDevices.get_devices so that the BraketDWaveSampler can use the ARN of an ONLINE D-Wave QPU if no ARN is given
=> infra: update version

test/integ_tests/gate_model_device_testing_utils.py
* modify tol for integ tests
* this is due to integ tests failing sometimes in the CI/CD workflow
* ran result_types_tensor_y_hermitian_testing 1000 times for local simulator, found that the absolute difference between the mean of the samples and the min and max was +/- ~0.3 with an expected mean of 1.4499810303182408. Increased tol accordingly, per https://numpy.org/doc/stable/reference/generated/numpy.allclose.html
* Ran integ tests
By submitting this pull request, …
=> infra: modify tol for integ tests

src/braket/_sdk/_version.py, src/braket/tasks/annealing_quantum_task_result.py, test/unit_tests/braket/tasks/test_annealing_quantum_task_result.py
* add handling for solution_counts=[] for annealing result
* tested using ocean plugin as well
=> fix: add handling for solution_counts=[] for annealing result

README.md
* Add D-Wave Advantage_system1 arn
=> documentation: Add D-Wave Advantage_system1 arn

src/braket/tasks/gate_model_quantum_task_result.py
* Update docstring for measurement_counts so that customers are made aware that the keys are unordered
=> documentation: Update docstring for measurement_counts

test/integ_tests/conftest.py
* change check for s3 bucket exists to head_bucket because for some cases, creation_date is None even when the bucket exists
* ran integ tests
=> infra: change check for s3 bucket exists

README.md
=> documentation: add sample notebooks link

src/braket/aws/aws_quantum_task.py, test/unit_tests/braket/aws/test_aws_quantum_task.py
* Add optimization to only poll during execution window
* Also added a parameter to configure whether to poll during execution window or not
* added and ran tests
=> change: Add optimization to only poll during execution window

src/braket/circuits/circuit.py, test/unit_tests/braket/circuits/test_circuit.py
* allow simultaneous measurement of commuting observables
* added tests, ran tests
=> change: Enable simultaneous measurement of observables with shared factors

CODEOWNERS
=> infra: update codeowners

README.md, src/braket/aws/__init__.py, src/braket/aws/aws_device.py, src/braket/aws/aws_quantum_task.py, src/braket/aws/aws_quantum_task_batch.py, src/braket/aws/aws_session.py, test/integ_tests/gate_model_device_testing_utils.py, test/integ_tests/test_simulator_quantum_task.py, test/unit_tests/braket/aws/common_test_utils.py, test/unit_tests/braket/aws/test_aws_device.py, test/unit_tests/braket/aws/test_aws_quantum_task.py, test/unit_tests/braket/aws/test_aws_quantum_task_batch.py, test/unit_tests/braket/aws/test_aws_session.py
Added methods to support running multiple tasks in parallel.
=> feature: Add support for batch execution

src/braket/aws/aws_device.py, src/braket/aws/aws_quantum_task.py, test/unit_tests/braket/aws/test_aws_quantum_task.py
=> feature: Enable explicit qubit allocation

test/integ_tests/conftest.py
=> fix: Correct integ test bucket

src/braket/aws/aws_device.py
*Description of changes:* Some docstrings in `aws_devices.py` were missing backticks or periods. 
=> doc: fix backticks, grammar for aws_device.py

src/braket/aws/aws_quantum_task.py
*Description of changes:* fix backticks, missing periods in quantum task docs
*Testing done:* tox passed locally
=> doc: fix backticks, missing periods in quantum task docs

src/braket/aws/aws_session.py
*Description of changes:* Added trailing periods to some lines so that all the docstrings have consistent formatting.
*Testing done:* tox passed locally
=> doc: add punctuation to aws_session.py

src/braket/aws/aws_quantum_task.py, test/unit_tests/braket/aws/test_aws_quantum_task.py
Revert to previous strategy of polling without checking windows
tox
=> change: remove window check for polling-- revert to polling at all times

src/braket/circuits/circuit.py, src/braket/circuits/observables.py, test/unit_tests/braket/circuits/test_circuit.py
=> fix: Remove redundant statement, boost coverage

test/unit_tests/braket/aws/common_test_utils.py, test/unit_tests/braket/aws/test_aws_quantum_task.py, test/unit_tests/braket/aws/test_aws_quantum_task_batch.py
=> infra: Raise coverage to 100%

CODEOWNERS, src/braket/aws/aws_device.py, test/unit_tests/braket/aws/test_aws_device.py
=> fix: Search for unknown QPUs

README.md
*Issue #, if available:* N/A
*Description of changes:* remove unneeded calls to sts from the README
*Testing done:* Ran unit and integ tests to ensure there were no regressions. No new tests needed for this README change.
=> documentation: remove unneeded calls to sts from the README

src/braket/aws/aws_device.py, test/unit_tests/braket/aws/common_test_utils.py, test/unit_tests/braket/aws/test_aws_device.py
=> change: Remove hardcoded device ARNs

test/unit_tests/braket/circuits/test_angled_gate.py, test/unit_tests/braket/circuits/test_gate.py
=> infra: very minor test changes

src/braket/circuits/gates.py
=> change: Use np.eye for identity

src/braket/circuits/quantum_operator.py, test/unit_tests/braket/circuits/test_gate.py, test/unit_tests/braket/circuits/test_quantum_operator.py
=> fix: Don't return NotImplemented for boolean

README.md
=> doc: Add note about AWS region in README

src/braket/circuits/gates.py, src/braket/circuits/observables.py, src/braket/circuits/quantum_operator_helpers.py
=> doc: Wording changes

.github/workflows/dependent-tests.yml, .github/workflows/pennylane-plugin-tests.yml
=> infra: Run unit tests for dependent packages

doc/examples-adv-circuits-algorithms.rst, doc/examples-braket-features.rst, doc/examples-hybrid-quantum.rst, doc/examples-ml-pennylane.rst, doc/examples-quantum-annealing-dwave.rst, doc/examples-simple-circuits-algorithms.rst
- Fixes broken links and referencing correct examples. 
=> Fix broken repository links

src/braket/aws/aws_quantum_task.py, test/unit_tests/braket/aws/test_aws_quantum_task.py
Roll back device parameter change for dwave that relies on internal schema updates
=> roll back dwave change

doc/examples-adv-circuits-algorithms.rst, doc/examples-getting-started.rst, doc/examples-hybrid-quantum.rst, doc/examples-quantum-annealing-dwave.rst, doc/examples.rst
=> documentation: Fix link, typos, order

examples/local_noise_simulation.py
At least on the latest version `Braket-DM` errors.
=> Fix simulator name in example

.github/workflows/python-package.yml, README.md, examples/local_noise_simulation.py, setup.py, src/braket/_sdk/_version.py, src/braket/circuits/__init__.py, src/braket/circuits/ascii_circuit_diagram.py, src/braket/circuits/circuit.py, src/braket/circuits/moments.py, src/braket/circuits/noise.py, src/braket/circuits/noise_helpers.py, src/braket/circuits/noises.py, src/braket/circuits/quantum_operator_helpers.py, src/braket/circuits/result_types.py, test/integ_tests/gate_model_device_testing_utils.py, test/integ_tests/test_local_noise_simulator.py, test/unit_tests/braket/circuits/test_ascii_circuit_diagram.py, test/unit_tests/braket/circuits/test_gates.py, test/unit_tests/braket/circuits/test_moments.py, test/unit_tests/braket/circuits/test_noise.py, test/unit_tests/braket/circuits/test_noise_helpers.py, test/unit_tests/braket/circuits/test_noises.py, test/unit_tests/braket/circuits/test_quantum_operator_helpers.py, test/unit_tests/braket/circuits/test_result_type.py, test/unit_tests/braket/circuits/test_result_types.py, tox.ini
=> feature: Noise operators

doc/examples-braket-features.rst
* Added a reference to the example notebook for noise simulation.
* Built the docs locally and validated that they render correctly.
=> documentation: Add reference to the noise simulation example notebook

src/braket/aws/aws_quantum_task.py, test/unit_tests/braket/aws/test_aws_quantum_task.py
Exclude null values from device parameters for annealing tasks
tox
=> exclude null values from device parameters for annealing tasks

src/braket/aws/aws_quantum_task.py, test/unit_tests/braket/aws/test_aws_quantum_task.py
=> fallback on empty dict for device level parameters

src/braket/circuits/qubit.py, test/unit_tests/braket/circuits/test_qubit.py
=> fix: Require qubit indices to be integers

setup.py, test/unit_tests/braket/aws/test_aws_device.py
Add json validation for device schema in unit tests
Checked integ tests and unit tests still pass. Changes are only to unit tests.
- [ x ] I have updated any necessary documentation, …
=> change: add json validation for device schema in unit tests

test/unit_tests/braket/aws/test_aws_quantum_task.py
change: Add json schema validation for dwave device schemas.
Updated unit tests
- [ x ] I have updated any necessary documentation, including …
=> change: Add json schema validation for dwave device schemas.

src/braket/circuits/observable.py, src/braket/circuits/observables.py, test/unit_tests/braket/circuits/test_observables.py
Flatten Tensor Products so that they appear as a list and not nested Tensor Products.
Unit tests added
- [ x ] I have updated any necessary documentation, including …
=> change: Flatten Tensor Products

README.md
=> doc: Add documentation for support

src/braket/aws/aws_quantum_task.py, src/braket/aws/aws_session.py, src/braket/circuits/__init__.py, src/braket/circuits/ascii_circuit_diagram.py, src/braket/circuits/circuit.py, src/braket/circuits/compiler_directive.py, src/braket/circuits/compiler_directives.py, src/braket/circuits/instruction.py, src/braket/circuits/moments.py, src/braket/circuits/noise_helpers.py, src/braket/circuits/operator.py, src/braket/circuits/quantum_operator.py, test/unit_tests/braket/aws/test_aws_quantum_task.py, test/unit_tests/braket/circuits/test_ascii_circuit_diagram.py, test/unit_tests/braket/circuits/test_circuit.py, test/unit_tests/braket/circuits/test_compiler_directive.py, test/unit_tests/braket/circuits/test_compiler_directives.py, test/unit_tests/braket/circuits/test_instruction.py, test/unit_tests/braket/circuits/test_quantum_operator.py
Introduces verbatim boxes, which allows users to tell the compiler not
to modify specified parts of the circuit.
=> feature: Verbatim boxes

setup.py
* Pin jsonschema version corresponding to schema draft-07 (which our Pydantic models use) [V441785199]
=> Fix: Pin jsonschema version

test/unit_tests/braket/aws/test_aws_device.py
=> fix: rigetti typo

doc/getting-started.rst
Found a minor spelling nit
none. Using edit on github functionality.
- [ x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) doc
- [ x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#commit-your-change)
=> documentation: fixed a spelling nit

setup.py
Pin Coverage 5.5
```tox -e unit-tests```
- [ x ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-sdk-python/blob/main/README.md) and [API …
=> Pin Coverage 5.5

src/braket/jobs/local/local_job_container_setup.py, test/unit_tests/braket/jobs/local/test_local_job_container_setup.py
remove reference to preview assets for local container setup
tox integ/unit
=> fix: remove extraneous reference from local job container setup

src/braket/aws/aws_session.py, test/unit_tests/braket/aws/test_aws_session.py
Limit search for default IAM role to the "/service-role/" path prefix.
Tox, running a job with default jobs role
=> feature: optimize IAM role retrieval

test/integ_tests/test_create_local_quantum_job.py, test/integ_tests/test_create_quantum_job.py
This reverts commit a59548da9fa704912819a3c3e850fc6344cdadf0.
=> fix: Enable jobs integration tests

src/braket/aws/aws_device.py, test/unit_tests/braket/aws/test_aws_device.py
*Issue #, if available:* 
#269
Added property `is_available` to `AwdDevice` that parses the availability window and current device status to return a boolean flag if the device is currently available.
Added unit tests in `test_aws_device.py` that mock various `datetime` values to test the various possible combinations of device windows. Ran `tox` to run unit test, linters, and docs.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> feature: Added is_available property to AwsDevice

.github/workflows/dependent-tests.yml, src/braket/aws/aws_quantum_task.py, src/braket/circuits/circuit_helpers.py, src/braket/circuits/gates.py, test/integ_tests/test_device_creation.py, test/unit_tests/braket/aws/common_test_utils.py, test/unit_tests/braket/aws/test_aws_quantum_task.py, test/unit_tests/braket/circuits/test_circuit_helpers.py, test/unit_tests/braket/circuits/test_gates.py
change: Oqc release
Testing was done in a private repo with these changes.
- [ x ] I have updated any necessary documentation, including …
=> change: Oqc release

src/braket/aws/aws_device.py, src/braket/jobs/image_uri_config/base.json, src/braket/jobs/image_uri_config/pl_pytorch.json, src/braket/jobs/image_uri_config/pl_tensorflow.json, test/integ_tests/test_device_creation.py, test/unit_tests/braket/aws/test_aws_device.py
feat: Oqc release
tox, tox integ tests
- [ x ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-sdk-python/blob/main/README.md) and [API …
=> feat: LHR region configuration

src/braket/aws/aws_device.py
https://github.com/aws/amazon-braket-sdk-python/issues/319
Specify DEVICE_REGIONS docs. This is not a variable that describes device specific regions but instead describes where Braket operates.
tox.
- [ x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#commit-your …
=> documentation: Specify DEVICE_REGIONS docs.

.github/workflows/dependent-tests.yml, .github/workflows/python-package.yml
* Update github workflow configuration to run on `feature/*` branches 
=> fix: Run github workflows on feature branches

src/braket/circuits/circuit.py, src/braket/circuits/compiler_directive.py, src/braket/circuits/compiler_directives.py, src/braket/circuits/gate.py, src/braket/circuits/gates.py, src/braket/circuits/instruction.py, src/braket/circuits/noise.py, src/braket/circuits/noises.py, src/braket/circuits/observable.py, src/braket/circuits/observables.py, src/braket/circuits/result_type.py, src/braket/circuits/result_types.py, src/braket/circuits/serialization.py, test/unit_tests/braket/circuits/test_circuit.py, test/unit_tests/braket/circuits/test_compiler_directive.py, test/unit_tests/braket/circuits/test_compiler_directives.py, test/unit_tests/braket/circuits/test_gate.py, test/unit_tests/braket/circuits/test_gates.py, test/unit_tests/braket/circuits/test_instruction.py, test/unit_tests/braket/circuits/test_noise.py, test/unit_tests/braket/circuits/test_observable.py, test/unit_tests/braket/circuits/test_observables.py, test/unit_tests/braket/circuits/test_result_type.py, test/unit_tests/braket/circuits/test_result_types.py
* Adds the ability to generate OpenQASM from Braket circuits. 
* The implementation doesn't cover every supported gate/result type/noise yet. It only covers the following components:
* Compiler Directives
* Circuit
* Gates (Only `Rx`)
* Instruction
* Noise (Only `BitFlip`)
* Observables (Only `I` and `Hermitian`)
* Result Types (Only `Expectation`)
* `tox -e unit-tests` succeeded.
* Validated that the generated circuits can be executed against the service.
```
rom braket.circuits import Circuit
from braket.circuits.serialization import IRType
from braket.aws import AwsDevice
c = Circuit().rx(0, 0.15).rx(7, 0.3)
r = c.to_ir(ir_type=IRType.OPENQASM)
print(r.source)
d = …
```
=> feat: Add support for generating OpenQASM from circuits

test/integ_tests/test_create_local_quantum_job.py
Add a try/finally wrapper around the local job tests, so that if they fail due to docker not running, the test still exits out of the directory it cd'ed into. Otherwise, the rest of the tests in the suite will be executed in the wrong directory, leading to other errors.
Integ tests pass. With docker off, all non-(local job) integ tests pass.
=> fix: add exception handling to local job test

src/braket/aws/aws_device.py, src/braket/aws/aws_quantum_task.py, src/braket/aws/aws_quantum_task_batch.py, src/braket/tasks/__init__.py, src/braket/tasks/boson_sampling_quantum_task_result.py, src/braket/tasks/local_quantum_task.py, src/braket/tasks/photonic_model_quantum_task_result.py, src/braket/tasks/quantum_task.py, test/unit_tests/braket/aws/common_test_utils.py, test/unit_tests/braket/aws/test_aws_quantum_task.py, test/unit_tests/braket/tasks/test_photonic_model_quantum_task_result.py
=> feat: Add support for photonic computations

test/integ_tests/test_create_quantum_job.py
Make sure failed integ test fails with AlgorithmError from the job script entry point, but do not verify status codes
integ test passes
=> fix: change failureReason string check to let test pass

src/braket/circuits/instruction.py
=> fix: remove print statement

.github/workflows/dependent-tests.yml, .github/workflows/python-package.yml, setup.py, src/braket/devices/local_simulator.py, src/braket/tasks/gate_model_quantum_task_result.py, test/unit_tests/braket/devices/test_local_simulator.py, test/unit_tests/braket/tasks/test_gate_model_quantum_task_result.py, tox.ini
Combining two feature branches into one containing both the openqasm local simulator and openqasm generation (rebasing a single commit from `feature/openqasm-local-simulator` onto `feature/openqasm_generation` as a new branch `feature/openqasm`).
Tox 100%
=> Openqasm local simulator (#354)

src/braket/circuits/gates.py, test/unit_tests/braket/circuits/test_gates.py
#329
Generate OpenQASM braket unitary pragma from BDK unitary gate
tox and manual testing on SV1
=> feature: openqasm generation for unitary matrices

src/braket/circuits/gates.py, test/unit_tests/braket/circuits/test_gates.py
=> feature: openqasm generation for unitary matrices (#389)

test/unit_tests/braket/circuits/test_gates.py
=> fix string format

src/braket/ahs/time_series.py, test/unit_tests/braket/ahs/test_time_series.py
=> Adding timestamp order

.github/workflows/dependent-tests.yml, setup.py, tox.ini
Point simulator dependency to feature branch now that dev branch is merged
=> point default simulator to feature branch

.github/workflows/python-package.yml, setup.py, tox.ini
Remove antlr build step and reenable windows testing
Windows tests in this PR
=> fix: remove manual build step and reenable windows build

src/braket/aws/aws_quantum_task.py, src/braket/aws/aws_session.py, src/braket/tracking/__init__.py, src/braket/tracking/pricing.py, src/braket/tracking/tracker.py, src/braket/tracking/tracking_context.py, src/braket/tracking/tracking_events.py, test/integ_tests/test_cost_tracking.py, test/unit_tests/braket/aws/test_aws_session.py, test/unit_tests/braket/tracking/test_pricing.py, test/unit_tests/braket/tracking/test_tracker.py, test/unit_tests/braket/tracking/test_tracking_context.py
=> feature: cost tracking implementation

CONTRIBUTING.md
=> docs: Update README to include guidance for integrations

.github/workflows/dependent-tests.yml, .github/workflows/python-package.yml, setup.py, src/braket/devices/local_simulator.py, src/braket/tasks/gate_model_quantum_task_result.py, test/integ_tests/gate_model_device_testing_utils.py, test/integ_tests/test_local_braket_simulator.py, test/integ_tests/test_local_noise_simulator.py, test/unit_tests/braket/devices/test_local_simulator.py, test/unit_tests/braket/tasks/test_gate_model_quantum_task_result.py, tox.ini
Cleaned up integ tests to run on openqasm and jaqcd for all local and managed sim tests.
To do this, I pulled in the reviewed bdk code for calling the openqasm local sim from the `feature/openqasm-local-simulator` branch and resolved conflicts with main. If the last commit with the testing passes review, then for git conflict reasons, we can go ahead and turn this branch into the openqasm feature branch and trim the others.
Note -- currently points tox towards a non-feature branch of the simulator which has some bug fixes waiting to go through PR; will need to update that target before merging (blocked by sim repo)
unit/integ
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're …
=> Unify local sim tests, features branches

.github/workflows/dependent-tests.yml, setup.py, tox.ini
Remove feature branch refs and point to new releases
tox
=> fix: point to new schema + simulator releases

setup.py
Update to latest sim release
gh actions - tox
=> fix: update simulator version

src/braket/tasks/gate_model_quantum_task_result.py
-0 -> 0 in result types to avoid weird edge case
existing tox, todo to add new tests
=> fix: handle -0 edge case in result type hash

.github/workflows/dependent-tests.yml
=> infra: Add SF plugin to dependent tests

.github/workflows/dependent-tests.yml, .github/workflows/python-package.yml
=> infra: Don't run tests on push to feature branches

src/braket/circuits/gates.py, test/unit_tests/braket/circuits/test_gates.py
Add GPi gate
Unit tests and local sim smoke test
=> feature: add GPi gate

src/braket/circuits/gates.py, test/unit_tests/braket/circuits/test_gates.py
Add GPi2 Ionq native gate
Unit testing
=> feature: add GPi2 gate

src/braket/circuits/angled_gate.py, src/braket/circuits/gates.py, test/unit_tests/braket/circuits/test_angled_gate.py, test/unit_tests/braket/circuits/test_gates.py
Add IonQ MS native gate
unit testing
=> feature: add ms gate

src/braket/circuits/gates.py
=> fix: misc fixes

src/braket/ahs/analog_hamiltonian_simulation.py, src/braket/ahs/atom_arrangement.py, src/braket/ahs/discretization_types.py, src/braket/ahs/driving_field.py, src/braket/ahs/field.py, src/braket/ahs/hamiltonian.py, src/braket/ahs/pattern.py, src/braket/ahs/shifting_field.py, src/braket/ahs/time_series.py, test/unit_tests/braket/ahs/test_analog_hamiltonian_simulation.py, test/unit_tests/braket/ahs/test_atom_arrangement.py, test/unit_tests/braket/ahs/test_driving_field.py, test/unit_tests/braket/ahs/test_field.py, test/unit_tests/braket/ahs/test_hamiltonian.py, test/unit_tests/braket/ahs/test_pattern.py, test/unit_tests/braket/ahs/test_shifting_field.py, test/unit_tests/braket/ahs/test_time_series.py
=> update: refactoring discretize.

src/braket/jobs/local/local_job.py, src/braket/jobs/local/local_job_container.py, test/unit_tests/braket/jobs/local/test_local_job.py, test/unit_tests/braket/jobs/local/test_local_job_container.py
=> fix: making local jobs stream output.

src/braket/circuits/gate.py, test/unit_tests/braket/circuits/test_gate.py
Update Jaqcd to_ir error message to be more accurate
unit tests and manual
=> fix: update to_jaqcd error message

setup.py
update sim version to include native gates
manual installation testing
=> feature: update sim version for native gates

src/braket/ahs/analog_hamiltonian_simulation.py, src/braket/ahs/atom_arrangement.py, src/braket/ahs/discretization_types.py, src/braket/ahs/driving_field.py, src/braket/ahs/field.py, src/braket/ahs/hamiltonian.py, src/braket/ahs/pattern.py, src/braket/ahs/shifting_field.py, src/braket/ahs/time_series.py, test/unit_tests/braket/ahs/test_analog_hamiltonian_simulation.py, test/unit_tests/braket/ahs/test_atom_arrangement.py, test/unit_tests/braket/ahs/test_driving_field.py, test/unit_tests/braket/ahs/test_field.py, test/unit_tests/braket/ahs/test_hamiltonian.py, test/unit_tests/braket/ahs/test_pattern.py, test/unit_tests/braket/ahs/test_shifting_field.py, test/unit_tests/braket/ahs/test_time_series.py
Implementing `AnalogHamiltonianSimulation.discretize` method
=> AHS discretize

src/braket/circuits/circuit.py, test/unit_tests/braket/circuits/test_circuit.py
=> fix: Simultaneous measurement of identity on all qubits

setup.py, src/braket/circuits/angled_gate.py, src/braket/circuits/gate.py, src/braket/circuits/gates.py, test/unit_tests/braket/circuits/test_angled_gate.py, test/unit_tests/braket/circuits/test_gate.py, test/unit_tests/braket/circuits/test_gates.py
Add support for IonQ native gates + verbatim mode
unit testing
=> feature: IonQ native gates

src/braket/aws/aws_session.py, test/unit_tests/braket/aws/test_aws_device.py, test/unit_tests/braket/aws/test_aws_session.py
#445
Copy profile name when copying AwsSession objects
Manual verification and updated unit tests
=> fix: copy profile name

src/braket/aws/aws_session.py
#453
Don't specify profile name for default profile
Unit tests passing
=> fix: don't provide profile name for default profile

src/braket/aws/aws_quantum_task.py, src/braket/devices/local_simulator.py, test/unit_tests/braket/devices/test_local_simulator.py
Fix input handling for device.run
unit + integ tests
=> fix: clean upp edge cases around simulator kwargs

src/braket/ahs/analog_hamiltonian_simulation.py, src/braket/ahs/atom_arrangement.py, test/unit_tests/braket/ahs/test_analog_hamiltonian_simulation.py, test/unit_tests/braket/ahs/test_atom_arrangement.py
=> Updating per changes in the schema.

setup.py, src/braket/devices/local_simulator.py
Allow neutral atom simulator to run at the SDK level
Allow local simulator to run AnalogHamiltonianSimulation. Related PR: https://github.com/aws/amazon-braket-schemas-python/pull/122
The example notebooks can be run successfully. The unit tests are not added yet, this is WIP. 
=> [WIP] Feature/ahs local sim

src/braket/devices/local_simulator.py, test/unit_tests/braket/devices/test_local_simulator.py
- If inputs are provided, update the program's copy instead of the original program for submitting it to device to run. 
tox
=> fix: update inputs on program's copy

.github/workflows/dependent-tests.yml, src/braket/devices/local_simulator.py, test/integ_tests/test_local_braket_simulator.py, test/unit_tests/braket/devices/test_local_simulator.py, tox.ini
Add the integration test for AHS simulator. Note that this is the minimal test needed which confirms that BDK can call the AHS simulator. For the tests that the simulator, either its component or as a whole, is working properly, they are contained in the unit tests for the simulator
The test for the change is passed
=> add integration test for AHS simulator

doc/examples-adv-circuits-algorithms.rst, doc/examples-hybrid-jobs.rst, doc/examples-ml-pennylane.rst
Example notebook folder names changed as part of this PR https://github.com/aws/amazon-braket-examples/pull/194
- Validated new links open to the appropriate example
- Ran unit tests
=> documentation: update example notebook links

src/braket/circuits/circuit_helpers.py
There is no braket.circuit module; update text to braket.circuits.
(I got a ModuleNotFoundError following the advice in this message)
=> fix: Fix import path in error message

.github/scripts/update_dependency.py, CHANGELOG.md, setup.cfg, setup.py, src/braket/aws/aws_device.py, src/braket/aws/aws_quantum_task.py, src/braket/aws/aws_quantum_task_batch.py, src/braket/circuits/ascii_circuit_diagram.py, src/braket/circuits/circuit.py, src/braket/circuits/observable.py, src/braket/circuits/observables.py, src/braket/circuits/result_type.py, src/braket/circuits/result_types.py, test/integ_tests/test_adjoint_gradient.py, test/unit_tests/braket/aws/common_test_utils.py, test/unit_tests/braket/aws/test_aws_device.py, test/unit_tests/braket/aws/test_aws_quantum_task.py, test/unit_tests/braket/circuits/test_ascii_circuit_diagram.py, test/unit_tests/braket/circuits/test_observable.py, test/unit_tests/braket/circuits/test_observables.py, test/unit_tests/braket/circuits/test_result_type.py, test/unit_tests/braket/circuits/test_result_types.py, tox.ini
Co-authored-by: Viraj Chaudhari <72896239+virajvchaudhari@users.noreply.github.com>
Co-authored-by: Aaron Berdy <berdy@amazon.com>
Co-authored-by: Jacob Feldman <jacofeld@amazon.com>
Co-authored-by: Katharine Hyatt <67932820+kshyatt-aws@users.noreply.github.com>
Co-authored-by: Milan <30416311+krneta@users.noreply.github.com>
Co-authored-by: Cody Wang <speller26@gmail.com>
Co-authored-by: Abe Coull <85974725+math411@users.noreply.github.com>
Co-authored-by: Stephen Face <60493521+shpface@users.noreply.github.com>
Co-authored-by: Kshitij Chhabra <kshitijc@users.noreply.github.com>
Co-authored-by: Cody Wang <speller26@gmail.com>
Co-authored-by: Peter Komar <pkomar@amazon.com>
Co-authored-by: Mao Lin <maonlinml@amazon.com>
Co-authored-by: Michael Abel …
=> feature: adjoint gradient

src/braket/circuits/observables.py, test/unit_tests/braket/circuits/test_ascii_circuit_diagram.py, test/unit_tests/braket/circuits/test_observable.py
Update property to match ascii characters in constructor
unit and manual testing
=> fix: remove ascii_characters dynamic property for sum observables

src/braket/circuits/angled_gate.py, src/braket/circuits/gates.py, test/unit_tests/braket/circuits/test_angled_gate.py
#489 
Update ascii symbols for angled gate adjoint
Unit and manual testing
=> fix: update ascii symbols for angled gate adjoint

test/unit_tests/braket/aws/test_aws_quantum_task_batch.py
=> fix: remove OS signaling from run_batch unit test

src/braket/circuits/result_types.py, test/integ_tests/test_density_matrix_simulator.py, test/unit_tests/braket/circuits/test_result_types.py
add `all` keyword
unit/integ tests. manual testing in all prod regions and local sim
=> fix: specify all for density matrix target

test/integ_tests/test_cost_tracking.py, test/integ_tests/test_density_matrix_simulator.py, test/integ_tests/test_device_creation.py, test/integ_tests/test_pulse.py
=> update: updating for Aspen-M3

src/braket/aws/aws_session.py, src/braket/circuits/noises.py, src/braket/tracking/tracker.py, test/integ_tests/test_pulse.py, test/unit_tests/braket/aws/test_aws_session.py, test/unit_tests/braket/circuits/test_noise_helpers.py
=> fix: copy session with env and profile.

.github/workflows/dependent-tests.yml, .github/workflows/python-package.yml
=> update: adding build for python 3.10

.github/workflows/dependent-tests.yml, .github/workflows/publish-to-pypi.yml, .github/workflows/python-package.yml, README.md
https://github.com/badges/shields/issues/8671
https://github.com/aws-samples/amazon-braket-algorithm-library/commit/40bf548380c56ce4fa95f88e5071ca532a677701
=> Gh actions

src/braket/tracking/tracker.py
=> doc: Add note to call result to estimate sim tasks

src/braket/circuits/angled_gate.py, test/unit_tests/braket/circuits/test_angled_gate.py
=> fix: Prevent float-FreeParameter comparison

README.md
It doesn't contain any useful information
=> doc: Remove black badge

setup.py
=> fix: Include setuptools in requirements

src/braket/devices/local_simulator.py, src/braket/tracking/tracker.py, test/unit_tests/braket/quantum_information/test_pauli_string.py
=> Take advantage of some nice Python 3.8 features

test/integ_tests/test_cost_tracking.py
Ignore boto error for cancelling a completed task
Verified the try/except logic by trying to cancel a completed task
=> test: make simulator tracking integ test more robust

test/integ_tests/test_create_quantum_job.py
unit tests and integ tests locally
=> fix: update job test for python3.8

README.md
*Issue #, if available:* n/a
*Description of changes:* Update README's supported Python versions and support info.
=> documentation: update README information

src/braket/ahs/__init__.py, src/braket/ahs/discretization_types.py, src/braket/timings/__init__.py
=> Export from ahs and timings modules

src/braket/circuits/noise_model/noise_model.py
=> doc: typo in noise_model.py

src/braket/circuits/moments.py, test/unit_tests/braket/circuits/test_moments.py
=> fix: support adding a single instruction to moments

src/braket/circuits/circuit.py, src/braket/circuits/gate.py, src/braket/circuits/gates.py, src/braket/circuits/instruction.py, src/braket/circuits/moments.py, test/integ_tests/test_cost_tracking.py, test/unit_tests/braket/circuits/test_circuit.py, test/unit_tests/braket/circuits/test_gate.py, test/unit_tests/braket/circuits/test_gates.py, test/unit_tests/braket/circuits/test_instruction.py
#523
Initial commit to add support for control modifiers
Unit testing and manual testing
=> feat: control modifier

src/braket/aws/aws_device.py, test/integ_tests/test_cost_tracking.py, test/unit_tests/braket/aws/test_aws_device.py
=> Use device-specific poll interval if provided

src/braket/circuits/gate.py, src/braket/circuits/gates.py, src/braket/circuits/instruction.py, test/unit_tests/braket/circuits/test_circuit.py, test/unit_tests/braket/circuits/test_gates.py, test/unit_tests/braket/circuits/test_instruction.py
Add support for raising gates to powers
Unit testing
=> feat: power modifier

src/braket/aws/aws_quantum_job.py
fix: order terminal states for quantum jobs
=> test: order terminal states for quantum jobs

setup.cfg, test/unit_tests/braket/aws/test_aws_quantum_job.py, tox.ini
test: fix tox parallel issues with unsorted sets
https://pytest-xdist.readthedocs.io/en/latest/known-limitations.html
=> test: fix tox parallel issues with unsorted sets

doc/conf.py
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language
We should consider internationalization later on.
=> fix: hardcode the language used by Sphinx instead of falling back on the default

doc/conf.py, doc/examples-adv-circuits-algorithms.rst, doc/examples-braket-features.rst, doc/examples-getting-started.rst, doc/examples-hybrid-jobs.rst, doc/examples-hybrid-quantum.rst, doc/examples-ml-pennylane.rst, setup.cfg, setup.py, src/braket/ahs/discretization_types.py, src/braket/ahs/driving_field.py, src/braket/ahs/shifting_field.py, src/braket/aws/aws_session.py, src/braket/circuits/angled_gate.py, src/braket/circuits/circuit.py, src/braket/circuits/gates.py, src/braket/circuits/noises.py, src/braket/circuits/observable.py, src/braket/circuits/observables.py, src/braket/parametric/free_parameter_expression.py, src/braket/pulse/pulse_sequence.py, src/braket/quantum_information/pauli_string.py, src/braket/timings/time_series.py, tox.ini
`open build/documentation/html/_apidoc/braket.circuits.html` and files fixed were viewed for correctness
=> docs: add a linter to check proper rst formatting and fix up incorrect docs

src/braket/aws/aws_quantum_task.py, test/unit_tests/braket/aws/test_aws_quantum_task.py
=> fix: Remove `exclude_none` from device params

src/braket/jobs/config.py
=> fix: making kms key optional

test/integ_tests/test_cost_tracking.py, test/integ_tests/test_device_creation.py, test/unit_tests/braket/aws/common_test_utils.py
=> test: Rename ionQdevice to Harmony in tests

src/braket/jobs/quantum_job_creation.py, test/unit_tests/braket/jobs/test_quantum_job_creation.py
botocore error if kms is submitted when None
Manual verification of creating jobs with fix + existing integ tests should now pass
=> fix: exclude default none for kms

src/braket/circuits/gate.py, src/braket/circuits/gates.py, src/braket/circuits/instruction.py
escape bra-kets in new doc strings
manual testing
=> fix: backslashes

tox.ini
https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0.html#-recursive-or-rc
As of 5.0.0, this is not needed anymore
=> infra: remove flag that is no longer needed for isort

src/braket/circuits/ascii_circuit_diagram.py, test/unit_tests/braket/circuits/test_ascii_circuit_diagram.py
#523
Support ascii printing of gate powers
Unit test added
=> Power ascii

.github/workflows/dependent-tests.yml, .github/workflows/twine-check.yml
=> infra: Don't run dependent tests and twine check on push

src/braket/ahs/driving_field.py, src/braket/ahs/shifting_field.py, src/braket/aws/aws_device.py, src/braket/aws/aws_quantum_task.py, src/braket/aws/aws_quantum_task_batch.py, src/braket/aws/aws_session.py, src/braket/circuits/angled_gate.py, src/braket/circuits/basis_state.py, src/braket/circuits/gate.py, src/braket/circuits/gates.py, src/braket/circuits/instruction.py, src/braket/circuits/observable.py, src/braket/circuits/observables.py, src/braket/devices/local_simulator.py, src/braket/parametric/free_parameter_expression.py, src/braket/tasks/analog_hamiltonian_simulation_quantum_task_result.py, src/braket/timings/time_series.py, tox.ini
- Re-enabling Braket checkstyle checks and fix the existing issues. 
tox 
=> fix: re-enable & update content as per BCS

.github/workflows/check-format.yml
=> infra: add bcs checks to workflow

tox.ini
infra: cleanup the tox env between runs
=> infra: cleanup the tox env between runs

.github/workflows/dependent-tests.yml
stop testing against the strawberryfields plugin
Braket is not actively supporting development on this plugin. Removing from workflows.
=> infra: stop testing against the strawberryfields plugin

.github/workflows/python-package.yml
=> infra: Use final strategy index for Codecov run

.coveragerc
=> Exclude autograph from coverage

src/braket/circuits/unitary_calculation.py, test/unit_tests/braket/circuits/test_circuit.py
Pass gate modifiers to `to_unitary` to ensure computation is accurate
unit and manual testing
=> fix: pass gate modifiers to to_unitary

src/braket/experimental/autoqasm/api/api.py, src/braket/experimental/autoqasm/transpiler/transpiler.py, test/unit_tests/braket/experimental/autoqasm/test_transpiler.py
https://github.com/orgs/amazon-braket/projects/2/views/1?pane=issue&itemId=32618778
Increase code coverage to 100% for `transpiler` module of AutoQASM.
- Removes unused code, and code that apparently cannot be reached.
- Adds tests for various edge cases which are handled by the transpiler.
All existing and new tests pass.
=> change: increase autoqasm transpiler code coverage to 100%

src/braket/circuits/braket_program_context.py, src/braket/circuits/noises.py, src/braket/circuits/translations.py, test/unit_tests/braket/circuits/test_circuit.py
=> change: update noise operation in program context

setup.py
=> Update Braket dependencies

src/braket/aws/aws_device.py, src/braket/circuits/circuit.py, src/braket/pulse/ast/approximation_parser.py, test/unit_tests/braket/pulse/ast/test_approximation_parser.py
code coverage was not 100% in Approximation parser
Removed an impossible case and increase code coverage
added a unit test
=> Remove unnecessary branches in Approximation parser

setup.py, tox.ini
Description:
Build is failing: https://github.com/aws/amazon-braket-sdk-python/pull/613/files
Updated the local simulator with newer changes, now pointing to that newer commit
=> Update local simulator commit

src/braket/circuits/circuit.py, test/unit_tests/braket/circuits/test_circuit.py
multiple-parameter gate calibrations would be submitted in their parametric form.
Detecting parametric calibration based on parameters instead of angle.
=> Consider multiple parameter gates

src/braket/circuits/circuit.py
We are using copy and mutate input parameters where we could avoid it.
We create a temporary dict that we populate with new calibrations and update the main calibration dict.
Ran unit tests.
=> avoid mutating calibrations

src/braket/aws/aws_device.py, src/braket/aws/aws_quantum_task.py, src/braket/circuits/circuit.py, test/integ_tests/test_pulse.py, test/unit_tests/braket/aws/common_test_utils.py, test/unit_tests/braket/aws/test_aws_device.py, test/unit_tests/braket/circuits/test_circuit.py
=> fix: handle the optional calibration URL returning None

src/braket/circuits/braket_program_context.py, test/unit_tests/braket/circuits/test_circuit.py
Add Free parameter to the circuit
=> fix: Add `FreeParameter` support to `from_ir`

examples/job.py
containers do not yet have the `Devices` enum, so bringing that import into `__main__`
manual run of the example
=> fix: local import in job example

setup.py, tox.ini
n/a
Update commit hash to get updated version of mcm-sim branch from the simulator repo.
tox passes locally.
=> fix: update autoqasm dependency mcm-sim branch commit hash

test/integ_tests/test_device_creation.py
update devices enum test to automatically generate the expected names
verified integ test passes
=> test: update devices enum test

src/braket/circuits/braket_program_context.py, src/braket/parametric/free_parameter.py, test/unit_tests/braket/circuits/test_circuit.py
wrap symbols from the local simulator as free parameter expressions
unit and manual
=> feat: Support symbolic expressions in `from_ir`

setup.py, src/braket/jobs/quantum_job_creation.py, test/unit_tests/braket/jobs/test_quantum_job_creation.py
Pull latest container image as default
Unit and manual
=> fix: pull latest container image by default

src/braket/circuits/braket_program_context.py, test/unit_tests/braket/circuits/test_angled_gate.py, test/unit_tests/braket/circuits/test_circuit.py, test/unit_tests/braket/circuits/test_circuit_helpers.py, test/unit_tests/braket/circuits/test_compiler_directive.py, test/unit_tests/braket/circuits/test_gate.py, test/unit_tests/braket/circuits/test_gates.py, test/unit_tests/braket/circuits/test_instruction.py, test/unit_tests/braket/circuits/test_moments.py, test/unit_tests/braket/circuits/test_noise.py, test/unit_tests/braket/circuits/test_noise_helpers.py, test/unit_tests/braket/circuits/test_noises.py, test/unit_tests/braket/circuits/test_observable.py, test/unit_tests/braket/circuits/test_observables.py, test/unit_tests/braket/circuits/test_quantum_operator.py, test/unit_tests/braket/circuits/test_quantum_operator_helpers.py, test/unit_tests/braket/circuits/test_qubit.py, test/unit_tests/braket/circuits/test_result_type.py, test/unit_tests/braket/circuits/test_result_types.py
fix: change all tests in the circuit test path to use with pytest.raises
- Blindly believed that it would work
- Trusted the process
- Ran `tox -e unit-tests`
=> test: change all tests in the circuit test path to use with pytest.raises

src/braket/jobs/image_uri_config/base.json, src/braket/jobs/image_uri_config/pl_pytorch.json, src/braket/jobs/image_uri_config/pl_tensorflow.json, src/braket/jobs/image_uris.py, test/unit_tests/braket/jobs/test_image_uris.py
update `retrieve_image` to get the latest tag
unit and manual
=> feat: point image uri to latest tag

src/braket/circuits/braket_program_context.py
=> doc: update doc string for handle_parameter_value

src/braket/circuits/braket_program_context.py, test/unit_tests/braket/circuits/test_gates.py, test/unit_tests/braket/parametric/test_free_parameter_expression.py, test/unit_tests/braket/pulse/ast/test_approximation_parser.py
- Fixes flake8 and docstring issues found in few files. 
tox
=> doc: fix flake8 issues in tests

test/integ_tests/test_device_creation.py
update condition to filter out non-enum attributes of Devices
regression on python < 3.11
=> test: update devices enum integ test

src/braket/circuits/circuit.py, test/unit_tests/braket/circuits/test_circuit.py
=> Support OpenQASM `Program`s in `from_ir`

src/braket/circuits/braket_program_context.py
=> fix: don't wrap FreeParameterExpression input as string

src/braket/experimental/autoqasm/converters/break_statements.py, src/braket/experimental/autoqasm/errors.py, src/braket/experimental/autoqasm/transpiler/transpiler.py, test/unit_tests/braket/experimental/autoqasm/test_converters.py
Previously, break in a loop would silently have no effect. Now, raise an error.
Unit tests
=> Raise error if the user puts a break in their autoqasm loop

src/braket/experimental/autoqasm/api.py, test/unit_tests/braket/experimental/autoqasm/test_api.py
659
Improves autoqasm api/api.py coverage
Yes
=> change: improving autoqasm api.py coverage to 100%

CONTRIBUTING.md
=> docs: add mermaid diagram to describe the CI flow

setup.py, src/braket/aws/aws_device.py, src/braket/aws/aws_quantum_task.py, src/braket/circuits/__init__.py, src/braket/circuits/angled_gate.py, src/braket/circuits/circuit.py, src/braket/circuits/gate.py, src/braket/circuits/gate_calibrations.py, src/braket/circuits/gates.py, src/braket/parametric/free_parameter_expression.py, src/braket/pulse/ast/approximation_parser.py, src/braket/pulse/pulse_sequence.py, src/braket/pulse/waveforms.py, test/integ_tests/test_device_creation.py, test/integ_tests/test_pulse.py, test/unit_tests/braket/aws/common_test_utils.py, test/unit_tests/braket/aws/test_aws_device.py, test/unit_tests/braket/circuits/test_angled_gate.py, test/unit_tests/braket/circuits/test_circuit.py, test/unit_tests/braket/circuits/test_gate_calibration.py, test/unit_tests/braket/circuits/test_gates.py, test/unit_tests/braket/pulse/ast/test_approximation_parser.py, test/unit_tests/braket/pulse/test_pulse_sequence.py, test/unit_tests/braket/pulse/test_waveforms.py
=> feat: enable gate calibrations on supported devices

src/braket/experimental/autoqasm/instructions/__init__.py, src/braket/experimental/autoqasm/instructions/pulse_control.py, src/braket/experimental/autoqasm/instructions/qubits.py, src/braket/experimental/autoqasm/program/program.py, test/unit_tests/braket/experimental/autoqasm/test_pulse_control.py
https://github.com/orgs/amazon-braket/projects/2?pane=issue&itemId=35380579
- add pulse control operations
- add a `has_pulse_control` flag to program 
tox
=> feat: add pulse control operations to autoqasm

src/braket/experimental/autoqasm/api.py, src/braket/experimental/autoqasm/converters/break_statements.py, src/braket/experimental/autoqasm/converters/return_statements.py, src/braket/experimental/autoqasm/instructions/gates.py, src/braket/experimental/autoqasm/instructions/instructions.py, src/braket/experimental/autoqasm/instructions/pulse_control.py, tox.ini
Braket coding style linter was broken in `feature/autoqasm` branch due to a bug in the flake8 plugin, which is fixed by https://github.com/amazon-braket/amazon-braket-build-tools/pull/14. This PR fixes the issues that are uncovered in the feature/autoqasm branch once the linter plugin is working again.
tox passes.
=> doc: fix linter issues in feature/autoqasm after fixing BCS flake8 plugin

.github/dependabot.yml
=> infra: update dependendabot to use the infra prefix

src/braket/circuits/qubit_set.py
=> Move inline `_flatten` to top of `qubit_set.py`

README.md, doc/examples-braket-features.rst, doc/examples-hybrid-jobs.rst, src/braket/aws/aws_device.py, src/braket/aws/aws_quantum_job.py, src/braket/aws/aws_quantum_task.py, src/braket/aws/aws_quantum_task_batch.py, src/braket/aws/aws_session.py, src/braket/circuits/instruction.py, src/braket/devices/device.py, src/braket/devices/local_simulator.py, src/braket/jobs/config.py, src/braket/jobs/data_persistence.py, src/braket/jobs/local/local_job.py, src/braket/jobs/local/local_job_container.py, src/braket/jobs/local/local_job_container_setup.py, src/braket/jobs/metrics.py, src/braket/jobs/metrics_data/cwl_insights_metrics_fetcher.py, src/braket/jobs/metrics_data/cwl_metrics_fetcher.py, src/braket/jobs/quantum_job.py, src/braket/jobs/quantum_job_creation.py, src/braket/tasks/annealing_quantum_task_result.py, src/braket/tasks/gate_model_quantum_task_result.py, src/braket/tasks/local_quantum_task.py, src/braket/tasks/quantum_task.py, src/braket/tracking/tracker.py, test/integ_tests/test_create_local_quantum_job.py, test/integ_tests/test_create_quantum_job.py
Changed the naming of "job" and "task" to "hybrid job" and "quantum task"
- changed instances of "job" and "task" in the README and docstrings for API docs
- updated links to github example repos that will be changed following this PR: https://github.com/aws/amazon-braket-examples/pull/340
- minor refactoring for linters
- tox
- tox -e integ-tests
- [N/A ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ N/A] I have checked that my tests are not …
=> doc: standardize task and job naming to quantum task and hybrid job

src/braket/devices/devices.py
- Add the Aria 2 enum to devices
tox -e unit-tests
=> feat: add Aria2 enum

src/braket/circuits/circuit.py, src/braket/circuits/serialization.py, src/braket/parametric/free_parameter.py, src/braket/pulse/ast/qasm_transformer.py, test/integ_tests/test_adjoint_gradient.py, test/unit_tests/braket/aws/test_aws_quantum_task.py, test/unit_tests/braket/circuits/test_circuit.py, test/unit_tests/braket/circuits/test_gates.py, test/unit_tests/braket/circuits/test_noises.py, test/unit_tests/braket/circuits/test_observables.py, test/unit_tests/braket/circuits/test_result_types.py, test/unit_tests/braket/devices/test_local_simulator.py, test/unit_tests/braket/parametric/test_free_parameter.py
This reverts commit b158736a5f394fd709f4d12d6f5e0890d05dbbf6.
=> Revert "update: restricting parameter names to not collide with ones we use for OpenQASM generation."

.github/pull_request_template.md, CONTRIBUTING.md, README.md, doc/examples-adv-circuits-algorithms.rst, doc/examples-braket-features.rst, doc/examples-getting-started.rst, doc/examples-hybrid-jobs.rst, doc/examples-hybrid-quantum.rst, doc/examples-ml-pennylane.rst, doc/examples.rst, doc/index.rst, setup.py, tox.ini
=> doc: Replace aws org with amazon-braket

README.md
=> doc: add code contributors to the readme

README.md
=> doc: remove tailing backquotes

src/braket/aws/aws_device.py, test/unit_tests/braket/aws/test_aws_device.py
https://github.com/qiskit-community/qiskit-braket-provider/issues/114
Verified the issue in NBI
Unit tested.
=> fix: fixing search device when don't have access to a region.

src/braket/experimental/autoqasm/README.md
=> doc: Add FAQs to AutoQASM README

test/integ_tests/job_test_script.py
Integ test failing because latest changes aren't in the container
Integ test successful run (before original change that is being reverted)
=> fix: revert integ test changes

test/integ_tests/job_test_script.py
This reverts commit 3d62becd9e297fabdedc66fe671fa86702728e61.
Add back job helpers to integ tests now that the code is in the containers
Successful run of the modified integ tests
=> test: add job helpers to integ test

src/braket/jobs/environment_variables.py
fix doc string for get_hyperparameters
=> docs: fix helper docstring

src/braket/jobs/_entry_point_template.py
uncomment save_job_result import in template
manual verification
=> fix: uncomment import in template

.github/workflows/dependent-tests.yml, .github/workflows/python-package.yml, .readthedocs.yml, README.md, setup.py
=> infra: drop support for Python 3.8

src/braket/jobs/hybrid_job.py, src/braket/jobs/quantum_job_creation.py, test/unit_tests/braket/jobs/test_hybrid_job.py, test/unit_tests/braket/jobs/test_quantum_job_creation.py
prefix decorator jobs with "dec-"
unit and manual
=> feat: add dec- prefix to decorator jobs

src/braket/jobs/hybrid_job.py, src/braket/jobs/quantum_job_creation.py, test/unit_tests/braket/jobs/test_hybrid_job.py, test/unit_tests/braket/jobs/test_quantum_job_creation.py
revert job name prefix and improve source module prefix
unit and manual tests
=> feat: update source module prefix

src/braket/aws/aws_session.py, src/braket/jobs/hybrid_job.py, src/braket/jobs/image_uris.py, src/braket/jobs/quantum_job_creation.py, test/unit_tests/braket/aws/test_aws_session.py, test/unit_tests/braket/jobs/test_hybrid_job.py
validate python version matches between container and client
manual tests conducted (checked get_full_image_tag for all built in images). unit tests updated and added
=> feat: python version validation

test/integ_tests/test_create_quantum_job.py
Add try-catch around job definition to handle python version mismatch
verified integ tests passing in 3.9 and 3.10
=> fix: update integ test for non-py310

src/braket/aws/aws_quantum_job.py, test/unit_tests/braket/aws/test_aws_quantum_job.py
use `region` property to get region
unit tests
=> feat: use region property

README.md
=> doc: add the amazon braket tag in the stack exchange URL

setup.py
=> doc: update intended audience to include education and research

src/braket/jobs/hybrid_job.py
Add closing tics, harmonize representation of defaults.
*Issue #, if available:* N/A
*Description of changes:* Close some unclosed ticks, harmonize representation of defaults.
*Testing done:* N/A
=> doc: Fix some nits in the decorator doc string

src/braket/jobs/hybrid_job.py, test/unit_tests/braket/jobs/test_hybrid_job.py
bug fix: treat s3 config the same as s3 uri
manual test, unit test update
=> fix: add s3 config support for decorator jobs

.github/workflows/publish-to-pypi.yml
install setuptools as part of workflow, similar to recent change for twine workflow in #764
=> infra: install setuptools for pypi workflow

test/unit_tests/braket/aws/test_aws_device.py, test/unit_tests/braket/devices/test_local_simulator.py
=> fix: drop task count for batch task tests to 3

.github/workflows/check-format.yml
=> infra: pin the linter check to only use Python 3.9

src/braket/annealing/problem.py, src/braket/aws/aws_quantum_job.py, src/braket/aws/aws_quantum_task.py, src/braket/aws/aws_quantum_task_batch.py, src/braket/aws/aws_session.py, src/braket/circuits/circuit.py, src/braket/circuits/compiler_directive.py, src/braket/circuits/gate.py, src/braket/circuits/instruction.py, src/braket/circuits/moments.py, src/braket/circuits/noise.py, src/braket/circuits/observable.py, src/braket/circuits/result_type.py, src/braket/circuits/result_types.py, src/braket/jobs/config.py, src/braket/jobs/data_persistence.py, src/braket/jobs/hybrid_job.py, src/braket/jobs/local/local_job.py, src/braket/jobs/local/local_job_container.py, src/braket/jobs/metrics_data/cwl_insights_metrics_fetcher.py, src/braket/jobs/quantum_job.py, src/braket/jobs/quantum_job_creation.py, src/braket/pulse/pulse_sequence.py, src/braket/registers/qubit_set.py
=> fix: fixing some type hints for optional params

doc/examples-hybrid-jobs.rst
Fixing a broken link on the Hybrid Jobs doc page. (The target notebook was recently renamed.)
New link works.
=> doc: Fix broken link to hybrid jobs example notebook

src/braket/experimental/autoqasm/api.py
Remove `*args` from the signatures of the API decorators. Replace with single positional argument for decorated function. Enforce keyword-only for other decorator args, as before.
Unit tests passing
=> feat: remove *args from api decorators

src/braket/experimental/autoqasm/api.py
Update PR to utilize `_function_wrapper` in `aq.main`. Functionality is unchanged before/after this refactor
Demo:
```
from braket.experimental import autoqasm as aq
from braket.experimental.autoqasm.instructions import h, ry
y = 2
def fn(x) -> None:
if x:
h(2)
ry(angle=y, target=1)
decorator_no_parens = aq.main
decorator_parens = aq.main()
decorator_args = aq.main(num_qubits=3)
print("Testing no parens")
program = decorator_no_parens(fn)
print(program.to_ir())
print()
print("Testing parens")
program = decorator_parens(fn)
print(program.to_ir())
print()
print("Testing args")
program = decorator_args(fn)
print(program.to_ir())
print()
```
unit and manual tests
_Put an `x` in the boxes that apply. You can also fill these out …
=> utilize function wrapper

src/braket/devices/devices.py, test/integ_tests/test_cost_tracking.py
=> Add Forte 1 device

examples/hybrid_job.py, examples/reservation.py, src/braket/aws/aws_device.py, src/braket/aws/aws_quantum_job.py, src/braket/aws/aws_quantum_task.py, src/braket/aws/aws_quantum_task_batch.py, src/braket/aws/aws_session.py, src/braket/jobs/hybrid_job.py, src/braket/jobs/quantum_job_creation.py, src/braket/tracking/tracker.py, src/braket/tracking/tracking_events.py, test/integ_tests/test_reservation_arn.py, test/unit_tests/braket/aws/common_test_utils.py, test/unit_tests/braket/aws/test_aws_device.py, test/unit_tests/braket/aws/test_aws_quantum_job.py, test/unit_tests/braket/aws/test_aws_quantum_task.py, test/unit_tests/braket/aws/test_aws_quantum_task_batch.py, test/unit_tests/braket/jobs/test_hybrid_job.py, test/unit_tests/braket/jobs/test_quantum_job_creation.py, test/unit_tests/braket/tracking/test_tracker.py
Allowing Braket Direct job and task creation with reservation_arn
Unit tests and Integ tests
=> feat: Allow reservation ARN in task and job creation 

.github/workflows/code-freeze.yml
Allow code freeze to occur without `UNFROZEN_PREFIX` variable, which only allows critical fixes
Manual testing (see 3 workflow runs on this PR, latest commit)
- fix: fails
- fix(critical): passes
- feature/code-freeze passes with unfrozen prefix set
=> infra: no unfrozen prefix when variable is not present

src/braket/experimental/autoqasm/api.py
#836 
change `Program | partial` to `Program | Callable[..., Program]`
Manually verified that IDE (PyCharm) recognizes Program type correctly with and without parentheses.
=> feat: update type annotations for main decorator

setup.py, tox.ini
=> update mcm-sim version

src/braket/experimental/autoqasm/README.md, src/braket/experimental/autoqasm/doc/decorators.md
- Update documentation of `@aq.main` and `Program` usage to reflect change in calling pattern.
- Update GitHub URLs to point to `amazon-braket` org.
Tested that modified links and code snippets work.
=> doc: Update AutoQASM docs to reflect recent changes

src/braket/aws/aws_quantum_job.py, test/integ_tests/test_create_quantum_job.py, test/unit_tests/braket/aws/test_aws_quantum_job.py
Ensure the BDK doesn't use assumptions about the ARN format for jobs. Name is now extracted from metadata instead of being parsed from the ARN.
Unit and integ tests passing.
=> feat: update job name to use metadata

src/braket/jobs/quantum_job_creation.py, test/integ_tests/test_create_quantum_job.py, test/unit_tests/braket/jobs/test_quantum_job_creation.py
Add a timestamp to the S3 path of various job locations, such as source, input/output, checkpoints.
Should make sure to update defaults in console along with this PR
Unit tests and jobs integ tests, plus manual verification
=> feat: update S3 locations for jobs

setup.py, tox.ini
=> infra: remove flake8-rst-docstring linter

doc/conf.py, src/braket/aws/aws_device.py, src/braket/aws/aws_quantum_job.py, src/braket/aws/aws_quantum_task.py, src/braket/circuits/gate.py, src/braket/pulse/pulse_sequence.py, src/braket/quantum_information/pauli_string.py, test/unit_tests/braket/aws/common_test_utils.py, test/unit_tests/braket/test_imports.py
=> fix: add force flag for import testing

src/braket/quantum_information/pauli_string.py, test/unit_tests/braket/quantum_information/test_pauli_string.py
=> fix: Allow identities in PauliString observable

src/braket/experimental/autoqasm/api.py, src/braket/experimental/autoqasm/instructions/__init__.py, src/braket/experimental/autoqasm/instructions/gates.py, src/braket/experimental/autoqasm/instructions/instructions.py, src/braket/experimental/autoqasm/instructions/measurements.py, src/braket/experimental/autoqasm/instructions/qubits.py, src/braket/experimental/autoqasm/program/gate_calibrations.py, src/braket/experimental/autoqasm/program/program.py, src/braket/experimental/autoqasm/pulse/pulse.py, src/braket/experimental/autoqasm/types/__init__.py, src/braket/experimental/autoqasm/types/conversions.py, src/braket/experimental/autoqasm/types/types.py, test/unit_tests/braket/experimental/autoqasm/test_api.py, test/unit_tests/braket/experimental/autoqasm/test_types.py
#847 
Support qubit-type arguments in subroutines
Tests to be added. Currently verified with the following manual test:
```
from braket.devices import LocalSimulator
import braket.experimental.autoqasm as aq
from braket.experimental.autoqasm.instructions import h, cnot, measure
@aq.subroutine
def bell(q0: aq.Qubit, q1: aq.Qubit):
h(q0)
cnot(q0, q1)
@aq.subroutine
def n_bells(n: int, q0: aq.Qubit, q1: aq.Qubit):
for i in aq.range(n):
h(q0)
cnot(q0, q1)
@aq.main
def my_program():
bell(0, 1)
n_bells(5, 2, 3)
measure(range(4))
my_program.display()
print(LocalSimulator().run(my_program, shots=10).result().measurements)
"""
OPENQASM 3.0;
def bell(qubit q0, qubit q1) {
h q0;
cnot q0, q1;
}
def n_bells(int[32] n, qubit q0, qubit …
```
=> feat: support qubits as subroutine args

setup.py
=> infra: update schema version to latest in setup.py

src/braket/_sdk/_version.py, src/braket/aws/aws_device.py, src/braket/circuits/translations.py, src/braket/devices/device.py, src/braket/devices/local_simulator.py, test/unit_tests/braket/aws/common_test_utils.py, test/unit_tests/braket/aws/test_aws_device.py, test/unit_tests/braket/devices/test_local_simulator.py
Issue #, if available:
closes https://github.com/amazon-braket/amazon-braket-sdk-python/issues/851
- Support initializing DM simulator with a noise model, including local dm simulator and DM1. Noises are automatically applied to circuits when calling `device.run`.
- Validate supported pragma and throw error when adding noise model to devices that does not support noise. 
tox
=> feat: support noise model in dm simulators

src/braket/experimental/autoqasm/api.py, src/braket/experimental/autoqasm/converters/assignments.py, src/braket/experimental/autoqasm/converters/return_statements.py, src/braket/experimental/autoqasm/operators/__init__.py, src/braket/experimental/autoqasm/operators/assignments.py, src/braket/experimental/autoqasm/operators/return_statements.py, src/braket/experimental/autoqasm/program/program.py, src/braket/experimental/autoqasm/types/conversions.py, test/unit_tests/braket/experimental/autoqasm/test_api.py, test/unit_tests/braket/experimental/autoqasm/test_program.py, test/unit_tests/braket/experimental/autoqasm/test_return.py, test/unit_tests/braket/experimental/autoqasm/test_types.py
*Issue #, if available:* Closes #830
Add support for returning values from the main aq.function
New unit tests, updated existing tests.
=> feature: Add support for returning values from AutoQASM main

src/braket/experimental/autoqasm/instructions/qubits.py, src/braket/experimental/autoqasm/operators/utils.py, src/braket/experimental/autoqasm/program/program.py, test/unit_tests/braket/experimental/autoqasm/test_program.py
Remove deadcode from autoqasm and bring coverage back to 100%
=> maintenance: remove deadcode

test/integ_tests/conftest.py
=> fix: use the caller's account id based on the session

examples/hybrid_job.py, src/braket/aws/aws_quantum_job.py, src/braket/jobs/metrics_data/cwl_insights_metrics_fetcher.py, test/unit_tests/braket/aws/test_aws_quantum_job.py, test/unit_tests/braket/jobs/metrics_data/test_cwl_insights_metrics_fetcher.py
Search for new logs prefix `job-name/uuid` when interacting with jobs with the new ARN format
Regression testing and added a unit test. Will run integ tests once new ARN format is deployed
=> feat: update log stream prefix for new jobs

src/braket/jobs/metrics_data/cwl_insights_metrics_fetcher.py, test/unit_tests/braket/jobs/metrics_data/test_cwl_insights_metrics_fetcher.py
escape slash in metrics query
manual testing
=> fix: escape slash in metrics prefix

setup.py
=> infra: pin numpy to less than 2.x until we prepare for the migration

test/integ_tests/conftest.py
Fix the issue of ARNs replacing job names in the integ tests. The names assigned for the integ test are unique enough that we can rely on those to be a lookup key in search jobs results. This job arn is returned and used.
=> test: resolve integration test job arns becoming UUIDs

src/braket/aws/aws_session.py, test/unit_tests/braket/aws/test_aws_session.py
=> fix: store account id if already accessed

src/braket/aws/aws_quantum_task_batch.py
Batch execution was passing in iterable of iterables. This ensures we only iterate on single items.
`tox -e integ-tests` within the Braket Pennylane plugin repo as well as integ and unit tests within the SDK.
PL setup:
```
diff --git a/setup.py b/setup.py
index 0bb46f5..ac362de 100644
--- a/setup.py
+++ b/setup.py
@@ -34,7 +34,7 @@ setup(
packages=find_namespace_packages(where="src", exclude=("test",)),
package_dir={"": "src"},
install_requires=[
-        "amazon-braket-sdk>=1.47.0",
+        "amazon-braket-sdk @ git+https://github.com/amazon-braket/amazon-braket-sdk-python@batch_fix",^M
"pennylane>=0.34.0",
],
entry_points={
diff --git a/tox.ini b/tox.ini
index 8e923ad..50c7d1d 100644
--- a/tox.ini
+++ b/tox.ini
@@ -124,4 …
```
=> fix: batch tasking passing lists to single tasks

setup.py, tox.ini
This is part of the Pydantic 2.x migration
=> fix: temporarily pin the schemas version

setup.py
=> infra: change schemas constraint

.github/workflows/dependent-tests.yml, setup.py
=> fix: restore the dependent test back to pennylane

test/unit_tests/braket/ahs/test_analog_hamiltonian_simulation.py
backwards compatiblity for local detuning
=> fix: backwards compatiblity for local detuning

src/braket/ahs/local_detuning.py
=> fix: if rydberg local is not pulled, pass in None

src/braket/circuits/circuit.py
Update the example in the `measure` docstring to have the correct output.
`tox`
=> fix: correct the example in the measure docstring

setup.cfg
https://pytest-xdist.readthedocs.io/en/latest/distribution.html
`tox -e unit-tests`
=> infra: allow worksteal for testing with tox

test/integ_tests/conftest.py
=> fix: job fixture for endpoint support

src/braket/tasks/gate_model_quantum_task_result.py, test/unit_tests/braket/tasks/test_gate_model_quantum_task_result.py
n/a
`get_compiled_program` should work for IQM metadata too
new unit test
=> Add IQM to get compiled program convenience method

setup.py
=> infra: unpin numpy version

setup.py, src/braket/devices/device.py, src/braket/devices/local_simulator.py, test/unit_tests/braket/devices/test_local_simulator.py, tox.ini
As introduced in https://github.com/amazon-braket/amazon-braket-default-simulator-python/pull/264
=> feat: Use `run_multiple` for local batches

test/integ_tests/test_cost_tracking.py
=> test: Add Garnet to tracker integ test

src/braket/aws/aws_device.py, src/braket/devices/devices.py
- [] I have added tests that prove my fix is effective or that my feature works (if appropriate)
=> feat: Rigetti Ankaa

src/braket/devices/devices.py, test/integ_tests/test_device_creation.py, test/integ_tests/test_measure.py, test/integ_tests/test_reservation_arn.py
=> deprecation: Retire IonQ Harmony

setup.py
=> infra: update to cloudpickle 3.x

README.md, src/braket/devices/devices.py, test/integ_tests/test_cost_tracking.py, test/integ_tests/test_device_creation.py, test/integ_tests/test_pulse.py, test/unit_tests/braket/aws/common_test_utils.py, test/unit_tests/braket/aws/test_aws_device.py, test/unit_tests/braket/aws/test_aws_quantum_job.py, test/unit_tests/braket/jobs/test_quantum_job_creation.py
=> deprecation: Mark Aspen-M-3 as deprecated, replace with Ankaa-2 in tests

test/integ_tests/test_pulse.py
Follow-up to #1034 to update pulse integration tests for the Ankaa-2 device.
Ran modified integration tests locally, verified that they succeed.
=> fix: Update pulse integration tests for Ankaa-2 device

setup.py
SageMaker has currently pinned [cloudpickle==2.2.1](https://github.com/aws/sagemaker-python-sdk/blob/4b5659d191c089f5033c48147a3c2f1566e85fbc/pyproject.toml#L36), but has a pending issue to resolve it. In the meantime, this is needed to maintain compatibility with the amazon-braket-containers.
=> fix: Pin cloudpickle==2.2.1

setup.py
This allows for the new schema changes to be needed in later BDK versions
`tox`
=> infra: constrain schemas to >= 1.23.0

src/braket/parametric/free_parameter.py, test/integ_tests/test_device_creation.py, test/integ_tests/test_measure.py, test/unit_tests/braket/circuits/test_ascii_circuit_diagram.py, test/unit_tests/braket/circuits/test_unicode_circuit_diagram.py
Update format due to linter updates
unit tests
=> doc: linter updates

src/braket/jobs/hybrid_job.py, test/unit_tests/braket/jobs/test_hybrid_job.py
closes https://github.com/amazon-braket/amazon-braket-sdk-python/issues/1054
The implementation is ported from https://github.com/amazon-braket/amazon-braket-sdk-python/pull/855 and https://github.com/amazon-braket/autoqasm/pull/21. 
- Persist source code of all inner functions of the job decorated function, as py files
- Upload the py file to the job as input data
- Replace the source location of all inner functions to a path in the job
This change strictly only applies to remote job decorator. When using regular job (ie. without decorator) or no job, there is no change in user code, and there is no artifact about source code.
working example:
```
from braket.jobs import hybrid_job
@hybrid_job( …
```
=> feat: support nested decorator with CUDA-Q hybrid job

test/integ_tests/test_reservation_arn.py
Update the target device in the integ tests for reservation
unit test, integ test
=> test: update target device for reservation integ test

src/braket/devices/devices.py
Added Ankaa-3 to devices enum for upcoming launch
Yes - tox -e unit-tests
=> feature: added ankaa-3 to enum

src/braket/devices/devices.py
=> feat: Add Forte Enterprise 1

src/braket/aws/aws_device.py, test/unit_tests/braket/aws/test_aws_device.py
=> change: handling capability upgrade issues

src/braket/ahs/analog_hamiltonian_simulation.py, src/braket/aws/aws_device.py, src/braket/aws/aws_quantum_task.py, src/braket/aws/aws_quantum_task_batch.py, src/braket/aws/aws_session.py, src/braket/circuits/braket_program_context.py, src/braket/circuits/circuit.py, src/braket/circuits/compiler_directives.py, src/braket/circuits/gates.py, src/braket/circuits/noises.py, src/braket/circuits/result_types.py, src/braket/circuits/translations.py, src/braket/circuits/unitary_calculation.py, src/braket/devices/device.py, src/braket/devices/local_simulator.py, src/braket/error_mitigation/debias.py, src/braket/jobs/data_persistence.py, src/braket/jobs/local/local_job.py, src/braket/tasks/analog_hamiltonian_simulation_quantum_task_result.py, src/braket/tasks/annealing_quantum_task_result.py, src/braket/tasks/gate_model_quantum_task_result.py, src/braket/tasks/photonic_model_quantum_task_result.py
only rerunning linters, no code change
tox
=> infra: linter updates

.github/workflows/check-format.yml, .github/workflows/python-package.yml, .github/workflows/twine-check.yml
=> infra: add coverage to public-main

src/braket/circuits/translations.py, test/unit_tests/braket/experimental_capabilities/iqm/test_iqm_experimental_capabilities.py
support from_ir for cc_prx and measure_ff
tox
=> feat: support from_ir for cc_prx and measure_ff

src/braket/devices/devices.py
Added Emerald to devices enum for upcoming launch
Yes - tox -e unit-tests
=> feat: Add Emerald

test/integ_tests/test_measure.py
- [ x] I have read the [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) doc
- [ x] I used the PR title format described in [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md#PR-title-format)
- [ x] I have updated any necessary documentation, including [READMEs](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/README.md) and [API …
=> fix: positional param issue for shots in tests

.github/workflows/python-package.yml, src/braket/aws/aws_session.py, test/unit_tests/braket/aws/test_aws_session.py
=> fix: resolve failing tests on py312 on windows

setup.py
=> fix: update local sim version dependency

src/braket/aws/aws_quantum_task.py, src/braket/tasks/quantum_task.py, test/unit_tests/braket/aws/test_aws_quantum_task.py
=> fix: Return results for failed program sets

.github/workflows/publish-to-pypi.yml
https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
=> infra: Use PyPI environment when releasing

.github/workflows/publish-to-pypi.yml
=> infra: Update release env name

src/braket/circuits/unitary_calculation.py
=> fix: ensure gate_matrix dtype is complex for unitary matrices
