README.md

documentation: update README with PyPI instructions

---

src/braket/aws/aws_quantum_task.py
src/braket/tasks/gate_model_quantum_task_result.py
test/integ_tests/gate_model_device_testing_utils.py
test/integ_tests/test_local_braket_simulator.py
test/integ_tests/test_simulator_quantum_task.py
test/unit_tests/braket/aws/common_test_utils.py
test/unit_tests/braket/aws/test_aws_quantum_task.py

* Converted amplitude result types to a complex number.
* Added integration test for validating amplitudes for SV1. 
* Enabled integration tests for simulators for shots=0.
```
>>> import boto3
>>> from braket.aws import AwsDevice
>>> from braket.circuits import Circuit
>>>
>>> aws_account_id = boto3.client("sts").get_caller_identity()["Account"]
>>> c = AwsDevice("arn:aws:braket:::device/quantum-simulator/amazon/sv1")
>>> s3_folder = (f"amazon-braket-{aws_account_id}", "folder-name")
>>> c = Circuit().x(0).amplitude(state=["1"])
>>> task = device.run(c, s3_folder, shots=0)
>>> print(task.result().values[0])
{'1': (1+0j)}
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're …

fix: Convert amplitude result to a complex number

---

src/braket/aws/aws_quantum_task.py
test/integ_tests/gate_model_device_testing_utils.py
test/integ_tests/test_local_braket_simulator.py
test/integ_tests/test_simulator_quantum_task.py

When calling task.result(), task.async_result() was called in the same line and then passed as a parameter. This fix moves the call to async_result() to a preceding line.
Without this fix, calls to task.result() will fail if called from worker threads. The reason is that before this fix, get_event_loop() is called before the event loop is created in async_result(), in case the event loop doesn't already exist. Separating the call to async_result() ensures that the event loop is always created first if necessary.
Added integration test that fails before the change and succeeds afterwards.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …

fix: Call async_result() before calling asyncio.get_event_loop()

---

src/braket/circuits/circuit_helpers.py
test/unit_tests/braket/circuits/test_circuit_helpers.py

* Add error message for running a circuit without instructions. Before, for circuits without any gates (only observables, for example), an uninformative validation error is returned: "max() arg is an empty sequence"
* Added unit tests

fix: Add error message for running a circuit without instructions

---

test/integ_tests/conftest.py

* change bucket creation setup for integ tests because by just trying to create the bucket, we can get an error for too many buckets created even though the bucket already exists
* Ran integ tests

infra: Change bucket creation setup for integ tests

---

src/braket/aws/aws_quantum_task.py
test/unit_tests/braket/aws/test_aws_quantum_task.py

Add tags parameter to create quantum task
As part of integration with tags for braket, the create method accepts tags as a parameter. Adding the same here
Unit tests and Integration Tests succeeded

feature: support tags parameter for create method in AwsQuantumTask

---

src/braket/aws/aws_quantum_task.py
test/unit_tests/braket/aws/test_aws_quantum_task.py

Correctly cache status

---

src/braket/aws/aws_quantum_task_batch.py

Use the user-provided max_workers when fetching batched results

Fix: Use the user-provided max_workers when fetching batched results

---

src/braket/aws/aws_quantum_task_batch.py
test/unit_tests/braket/aws/test_aws_quantum_task_batch.py

`AwsQuantumTaskBatch.results()` currently takes in a keyword `retry` that indicates whether the results are to be refetched from S3. This is misleading because it could suggest that failed tasks will be retried (they are not), and also doesn't match our previous use of `use_cached_value` in `AwsQuantumTask` to indicate whether cached results should be used or not.
This PR changes the method argument to use `use_cached_value` instead. Unfortunately, it is a breaking change (if used as a positional argument, the boolean value will need to be flipped).
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is …

Fix: Change AwsQuantumTaskBatch.results() to take in the keyword use_cached_value instead of retry.

---

README.md
examples/bell.py
examples/debug_bell.py

Instead of listing available devices, the README now links to the Amazon
Braket developer guide. The prevents the need to change the README with
each new device.
Also changed the bucket used in examples from amazon-braket-output-<ID>
to amazon-braket-<ID>, the correct default bucket name.

documentation: Point README to developer guide

---

src/braket/aws/aws_device.py
src/braket/aws/aws_quantum_task_batch.py
test/unit_tests/braket/aws/test_aws_quantum_task_batch.py

Move the defaults for the `max_parallel` keyword for task batches to `AwsDevice`.
This will allow setting device-dependent defaults, like we currently do for `shots`.

Fix: Move defaults for max_parallel in AwsQuantumTaskBatch to AwsDevice

---

src/braket/aws/aws_quantum_task_batch.py

*Description of changes:* Added backticks and trailing periods for docstrings in the batched tasks file.
*Testing done:* tox passes locally

doc: backticks for batching tasks

---

README.md
src/braket/aws/aws_device.py
test/integ_tests/gate_model_device_testing_utils.py
test/integ_tests/test_simulator_quantum_task.py
test/integ_tests/test_tensor_network_simulator.py
test/unit_tests/braket/aws/common_test_utils.py
test/unit_tests/braket/aws/test_aws_device.py

AwsDevice.get_devices() creates a new AwsSession object for each region
that devices can be found and then creates an AwsDevice object for each
device found, using the last AwsSession created. However, there is no
guarantee that each device even exists in the session's region.
This is fine for QPUs, since the correct region is automatically used;
this is not the case for simulators, which have been assumed to exist in
every region. TN1 does not exist in every region, get_devices() will
always fail.
This commit fixes the bug by only instantiating simulators that are
available in the current region in AwsDevice.get_devices.
Also added integ tests for TN1.
_Put an `x` in the boxes that apply. You can also fill these out after …

fix: Use current region for simulators in get_devices

---

src/braket/aws/aws_device.py
test/unit_tests/braket/aws/test_aws_device.py

Do not call search_devices at all if requesting simulators only and in a different region.

fix: Do not search for simulators in wrong region

---

src/braket/aws/aws_device.py
test/unit_tests/braket/aws/test_aws_device.py

Overhauls get_devices logic to filter regions based on ARNs instead of providers. This future-proofs the SDK for QPUs added to new regions.
By getting rid of the region lists, this also fixes a bug where the wrong devices would be returned for regions other than us-west-2, which was the first region in the list.
[build_files.tar.gz](https://github.com/aws/amazon-braket-sdk-python/files/5727106/build_files.tar.gz)
By submitting this pull request, I confirm that my contribution is made under …

fix: Get regions for QPUs instead of providers

---

test/integ_tests/test_tensor_network_simulator.py

* `random.randint(a, b)` picks a random integer `N` such that `a <= N <= b`. In case the `h_qubit` picked is 24 (in `test_qft_iqft_h`), the expected result of `"0" * num_qubits` is incorrect.
* Updated the `h_qubit` to be picked in the range [0, 24) instead.
- [ x ] I used the commit message format described in …

fix: Update range of random qubit in test_qft_iqft_h

---

src/braket/circuits/circuit.py
src/braket/circuits/result_type.py
src/braket/circuits/result_types.py
src/braket/tasks/gate_model_quantum_task_result.py
test/unit_tests/braket/tasks/test_gate_model_quantum_task_result.py

use a dict to hold the result types to speed up checking if a result type is in _result_types. result_types property still interfaces as a list. Python 3.7+ officially guarantees order for dicts, so result_types is expected to be in order
also edit gate_model_quantum_task_result to add a dict mapping result type to index, as well as ensuring consistency regarding result type in the implementation
By submitting this pull request, I confirm that my contribution is made …

change: update result_types to use hashing

---

src/braket/circuits/observable.py
src/braket/circuits/observables.py
src/braket/circuits/quantum_operator.py
src/braket/tasks/gate_model_quantum_task_result.py
test/unit_tests/braket/circuits/test_observable.py
test/unit_tests/braket/circuits/test_observables.py
test/unit_tests/braket/tasks/test_gate_model_quantum_task_result.py

Currently, whenever an observable is instantiated, _all_ of its
eigenvalues are calculated and stored in an array. This means a
tensor product on n qubits will instantiate an array of length 2^n,
which obviously isn't scalable for large n.
This change calculates the eigenvalues only at desired indices.

change: More scalable eigenvalue calculation

---

src/braket/circuits/gates.py
test/unit_tests/braket/circuits/test_circuit.py
test/unit_tests/braket/circuits/test_gates.py
test/unit_tests/braket/circuits/test_observables.py

Before, `Unitary.__eq__` only checked that the types were the same.
This change ensures that the actual matrices are also equivalent.

fix: Unitary equality checks matrix

---

src/braket/circuits/angled_gate.py
test/unit_tests/braket/circuits/test_angled_gate.py

#213
Currently `AngledGate` does not check for angle equality (just type equality) in `__eq__`. This change fixes this.

fix: AngledGate equality checks angles

---

.coveragerc
src/braket/aws/aws_session.py
test/unit_tests/braket/aws/test_aws_session.py

* Updated `user_agent` field to append the Braket SDK, Braket Schemas and Notebook Instance versions. Notebook instance version information is currently unavailable and a value of 0 is used for now.
* `.coveragerc` was updated to work around the following error:
```
No source for code: '/Volumes/workplace/chhabrk/sdkn/amazon-braket-sdk-python/src/braket/_schemas/__init__.py'.
Aborting report output, consider using -i
```
* Validated that the correct user agent was being set both for local installations and notebook instances.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what …

change: Update user_agent for AwsSession

---

src/braket/aws/aws_quantum_task.py

This PR fixes two bugs when polling statuses.
First, in _update_status_if_nonterminal we check whether metadata is absent by comparing self._metadata with None. This check will always fail, since self._metadata starts out as the empty dict {}.
Second, when calling task.result() we always start out by checking for task completion before entering the async loop, even if we've never polled before. This PR changes the behavior to enter the async loop directly if polling hasn't been done.
Unit tests.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for …

fix: remove unneeded get_quantum_task calls

---

src/braket/aws/aws_quantum_task.py

Add check for completeness in task.result() and directly download the result if available
Will be adding more commits to this pull request for related changes
unit/integ

fix: check for task completion before entering async event loop

---

src/braket/aws/aws_quantum_task_batch.py

- In the quantum task batch requests, in some cases, when the number of the max parallel parameter was less than the number of tasks submitted, we would create unnecessary threads and use our own mechanism for gating them. I changed this so we rely on the ThreadPoolExecutor for limiting the number of threads that we use.
- tox

fix: stop manually managing waiting treads in quantum task batch requests

---

src/braket/annealing/problem.py
src/braket/aws/aws_quantum_task.py
src/braket/circuits/observables.py
test/unit_tests/braket/aws/test_aws_quantum_task.py

AWS Internal
Added /taskArn to string representation of AwsQauntumTask. This is to help users quickly understand that the id and task ARN are the same. Also added single quotes around the ARN to further clarify.
ran unit tests and integ tests
- [x ] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) doc
- [ x] I used the commit message format described in …

fix: Added /taskArn to id field in AwsQuantumTask __repr__

---

src/braket/aws/aws_device.py
test/unit_tests/braket/aws/test_aws_device.py

- Copy the boto3 session using the default botocore session, unless the customer created the session using explicit credentials. This should allow sessions to refresh credentials if they are open for more than an hour.
- tox
- Verified that explicit credentials still work as before
- Verified that copied sessions will use the refreshed credentials after the previous ones expire

fix: copy the boto3 session using the default botocore session

---

src/braket/circuits/angled_gate.py
src/braket/circuits/gate.py
src/braket/circuits/gates.py
src/braket/circuits/noise.py
src/braket/circuits/noise_helpers.py
src/braket/circuits/noises.py
src/braket/circuits/quantum_operator.py
test/unit_tests/braket/circuits/test_gates.py
test/unit_tests/braket/circuits/test_noise_helpers.py
test/unit_tests/braket/circuits/test_noises.py
test/unit_tests/braket/circuits/test_quantum_operator.py

Introduced `fixed_qubit_count` so customers don't need to instantiate a gate or noise operation to see its qubit count. Also fixed a bug when checking compatibility of gate and noise qubit counts, where the gate could always be instantiated with no arguments, which obviously fails for parametrized gates.

fix: Get qubit count without instantiating op

---

src/braket/circuits/qubit.py
test/unit_tests/braket/circuits/test_qubit.py

Check value rather than type to make sure qubit index is an int.
unit test added

allow integer valued non-int type for qubit index

---

src/braket/circuits/circuit.py

252
The issue was that repr() output has a syntax error: `...]result_types': ...`. The fix was to add `, '` so it would read `...], 'result_types': ...`.
Yes

fix: Result Type syntax in repr

---

test/integ_tests/test_local_braket_simulator.py

* Added a test for catching changes to device names. The local simulator class renaming caused one of the example notebooks to break. This test would ensure that we detect such changes in the future.
* `tox -e integ-tests -- -k 'test_local_simulator_device_names'` succeeded.

change: Add test for local simulator device names

---

src/braket/circuits/circuit.py
src/braket/circuits/circuit_helpers.py
test/integ_tests/gate_model_device_testing_utils.py
test/integ_tests/test_local_braket_simulator.py
test/integ_tests/test_local_noise_simulator.py
test/integ_tests/test_simulator_quantum_task.py
test/unit_tests/braket/circuits/test_circuit.py
test/unit_tests/braket/circuits/test_circuit_helpers.py

Allows arbitrary observables to be attached to a circuit, allowing, for example, the simultaneous calculation of all terms of a qubit Hamiltonian when `shots=0`. However, running such a circuit with `shots>0`, will throw an exception, as observables must commute to be measured (sampled) simultaneously; in fact, here the observables must be either identical or the identity.
By submitting this pull request, I confirm that my contribution is made under the terms of the …

feature: Calculate arbitrary observables when `shots=0`

---

src/braket/circuits/circuit.py
src/braket/circuits/instruction.py
src/braket/circuits/moments.py
src/braket/circuits/result_type.py

Changed mutable default arguments (i.e. `def func(a={})`) to immutable ones (`def func(a=None)`) to avoid [unexpected bugs](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) down the line.

fix: Remove immutable default args

---

doc/requirements.txt

docutils 0.18 was released on October 26, 2021, and with it came some [breaking changes](https://github.com/readthedocs/readthedocs.org/issues/8616) for sphinx, and in turn [readthedocs builds](https://readthedocs.org/projects/amazon-braket-sdk-python/builds/15168485/). To keep doc builds working, docutils will be constrained to versions below 0.18.
- [] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-sdk-python/blo …

infra: Pin docutils<0.18 in doc requirements

---

test/integ_tests/test_create_local_quantum_job.py
test/integ_tests/test_create_quantum_job.py

fix: Skip jobs integration tests

---

src/braket/_sdk/_version.py
src/braket/circuits/gates.py
test/unit_tests/braket/circuits/test_gates.py
tox.ini

This makes certain circuits, like CHSH, more straightforward. This commit works in line with the following branches (also committed, separately):
https://github.com/unprovable/amazon-braket-schemas-python.git@ctrl-v-gate
https://github.com/unprovable/amazon-braket-default-simulator-python.git@ctrl-v-gate
Added the controlled version of the sqrt(NOT) gate, in Braket's parlance this is the V-gate, and so it is named the 'CV-gate' in this PR. I have also made the relevant changes on similarly named branches in the `schemas` and `default-simulator` repos. These are located:
* https://github.com/unprovable/amazon-braket-schemas-python.git@ctrl-v-gate
* https://github.com/unprovable/amazon-braket-default-simulator-python.git@ctrl-v-gate
(I'll …

feature: added controlled-sqrt-not gate

---

src/braket/circuits/noise.py
src/braket/circuits/noises.py
src/braket/circuits/observables.py
src/braket/circuits/quantum_operator_helpers.py
src/braket/circuits/unitary_calculation.py
src/braket/tasks/gate_model_quantum_task_result.py
test/integ_tests/test_tensor_network_simulator.py
test/unit_tests/braket/circuits/test_noise.py
test/unit_tests/braket/circuits/test_noises.py
test/unit_tests/braket/circuits/test_observables.py

Adding TwoQubitPauliChannel and MultiQubitPauliNoise. 
Added TwoQubitPauliChannel to existing tests.

feature: adding TwoQubitPauliChannel

---

src/braket/aws/aws_device.py
src/braket/aws/aws_quantum_job.py
test/unit_tests/braket/aws/test_aws_device.py
test/unit_tests/braket/aws/test_aws_quantum_job.py

* Update the region switching logic to account for regional device arns.

feat: Update region switching for regional device arns 

---

src/braket/aws/aws_quantum_job.py
src/braket/jobs/quantum_job_creation.py
test/unit_tests/braket/jobs/test_quantum_job_creation.py

- Currently our docs say we automatically stringify hyperparameters passed in but we do not. This is a fix to do that.
- tox integ and unit tests run successfully
- I manually tested creating a job with and without non-string values
- [ x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/main/CONTRIBUTING.md) doc
- [ x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-sdk-python/blob/m …

fix: stringify hyperparameters automatically

---

src/braket/aws/aws_device.py
src/braket/aws/aws_quantum_job.py
test/unit_tests/braket/aws/test_aws_quantum_job.py

While device ARN validation is handled by the service, we do some basic preprocessing that assumes the ARN will be of a certain format (ie. having at least 3 :'s). Previously, an ARN that doesn't meet this requirement would cause a crash in the BDK; now this throws an error gracefully.
Added a unit test.

fix: add device arn error handling for badly formed ARNs

---

src/braket/aws/aws_quantum_job.py
src/braket/jobs/quantum_job_creation.py
test/unit_tests/braket/aws/test_aws_quantum_job.py

Adds a parameter to easily populate the hyperparameters of CreateJob for the use of sagemaker data parallelism.
unit tests, integ tests

feat: add convenient selection of data parallelism

---

src/braket/jobs/metrics_data/cwl_insights_metrics_fetcher.py
src/braket/jobs/metrics_data/log_metrics_parser.py
test/unit_tests/braket/jobs/metrics_data/test_cwl_insights_metrics_fetcher.py
test/unit_tests/braket/jobs/metrics_data/test_log_metrics_parser.py

Metrics logged from distributed jobs are additionally tagged with a node id like, `[1,mpirank:4,algo-1]<stdout>:Metrics - cost=5;...`. This change is to also read logs with this tag on the metrics and to use this tag as an additional pivot so that two nodes do not overwrite each other's metrics.
unit-tests, integ-tests, local testing with a job with multinode metric logs.

feat: Support jobs metrics with multiple nodes

---

src/braket/aws/aws_session.py
test/unit_tests/braket/aws/test_aws_session.py

Run the exact same code in prod/pre-prod just by setting an environment variable for region/stage
```python
import boto3
from braket.aws import AwsDevice, AwsSession
from braket.circuits import Circuit
endpoint = "https://some-endpoint.com"
braket_client = boto3.client("braket", region_name="us-west-2", endpoint_url=endpoint)
aws_session = AwsSession(braket_client=braket_client)
device = AwsDevice("arn:aws:braket:::device/quantum-simulator/amazon/sv1", aws_session=aws_session)
bell = Circuit().h(0).cnot(0, 1)
task = device.run(bell, shots=100)
```
```bash
export BRAKET_ENDPOINT="https://some-endpoint.com" && export AWS_REGION=us-west-2
```
```python
from braket.aws import AwsDevice
from braket.circuits import Circuit
device = …
```

feat: allow user to set region+endpoint through env variables

---

src/braket/jobs/quantum_job_creation.py

Allow role_arn parameter for jobs to be set via an environment variable
Verified that jobs the role arn will be parsed from the env variable and existing functionality still works.

feat: allow job role to be set via env variable

---

src/braket/aws/aws_quantum_task.py
test/unit_tests/braket/aws/test_aws_quantum_task.py

This fix will unblock the customer from validating the suggestion in this issue : https://github.com/aws/amazon-braket-sdk-python/issues/348 
Removing validation for disable_qubit_rewiring and letting the service handle it.
It seems like this check was done as an optimization, since the values should be validated service-side. I'm removing this because different devices handle verbatim differently and some don't require disable_qubit_rewiring for verbatim (in fact, they don't support the flag at all). Rather than trying to handle these differences client side (especially in AwsTask, rather than AwsDevice), I think we can remove the check and let the service handle it.
***Note:*** As a result of this change, customers will no longer get a …

fix: removing validation for disable_qubit_rewiring

---

setup.py

Remove the coverage dependency from the install dependencies to allow
better coexistence with other libraries.
The dependency is still pinned in the test extra so that it can be used
during the SDK testing process.
Executed the unit tests using:
```bash
pip install -U pip setuptools wheel
pip install tox
pip install '.[test]'
```

change: pin coverage dependency only for test extra

---

src/braket/aws/aws_device.py
src/braket/aws/aws_session.py
test/unit_tests/braket/aws/test_aws_device.py
test/unit_tests/braket/aws/test_aws_session.py

* Exposed the `aws_session` for an AwsDevice as a property.
* Added a method `add_braket_user_agent` for updating the UserAgent header for the Braket client. 
* `tox -e unit-tests` succeeded.
* Updated Pennylane plugin and verified that the corresponding headers are being set correctly.

feat: Add method for updating the user agent for braket client

---

src/braket/circuits/gates.py
test/unit_tests/braket/circuits/test_gates.py

fix: format a - bi when negative imaginary component

---

src/braket/circuits/observables.py
src/braket/circuits/result_types.py
test/integ_tests/gate_model_device_testing_utils.py
test/integ_tests/test_local_braket_simulator.py
test/integ_tests/test_local_noise_simulator.py
test/integ_tests/test_simulator_quantum_task.py
test/unit_tests/braket/circuits/test_observables.py
test/unit_tests/braket/circuits/test_result_types.py
tox.ini

Add openqasm generation step to openqasm integ tests.
tox -e integ-tests -- -k openqasm

add generation step to openqasm integ tests

---

src/braket/aws/aws_quantum_task.py
test/unit_tests/braket/aws/test_aws_quantum_task.py

Raise an error when a user tries to use OpenQASM Program inputs for an AWS quantum task.
unit test added, manually tested

feature: raise error if user tries to use inputs for the service

---

src/braket/circuits/circuit.py
test/integ_tests/test_local_braket_simulator.py
test/integ_tests/test_local_noise_simulator.py

Make sure there is no local sim openqasm features warning for integ tests
integ

assert no sim warning for integ tests

---

test/unit_tests/braket/tasks/test_photonic_model_quantum_task_result.py

* Avoid mutation of a fixture which is being reused across multiple object. This was working earlier as Pydantic had inadvertently released a change for deep copying, but have now reverted to the old behavior of shallow copying.

fix: Avoid mutation of fixtures

---

src/braket/jobs/local/local_job_container.py
test/unit_tests/braket/jobs/local/test_local_job_container.py

*Issue #440 *
Updated Path calls to PurePosixPath for the destination directory.
Tested the fix as described in the issue in Windows and WSL.
[integ-aws-win-20220916T1742.log](https://github.com/aws/amazon-braket-sdk-python/files/9590481/integ-aws-win-20220916T1742.log)
[integ-aws-wsl-20220916T1758.log](https://github.com/aws/amazon-braket-sdk-python/files/9590485/integ-aws-wsl-2 …

fix: LocalQuantumJob.create() fails  on Windows

---

src/braket/ahs/atom_arrangement.py
test/unit_tests/braket/ahs/test_analog_hamiltonian_simulation.py

`AtomArrangement.add` converts the `coord` argument to a tuple before constructing an `AtomArrangementItem`. This enables passing numpy arrays of shape `(2,)` to to `add`. Without this conversion, the `add` would not fail, but calling `to_ir` on the `AnalogHamiltonianSimulation` object containing the atom arrangement in question would fail.
Yes. See `test_converting_numpy_array_sites_to_ir` in unit_tests/braket/ahs/test_analog_hamiltonian_simulation.py.
By submitting this pull request, I …

fix: allow using numpy arrays as atom sites

---

src/braket/ahs/atom_arrangement.py
test/unit_tests/braket/ahs/test_analog_hamiltonian_simulation.py

When the caller is doing `AtomArrangement.add(coord, site_type)`, both `coord` and `site_type` get validated for type and value.
Yes, the following tests (in test_analog_hamiltonian_simulation.py) check the correct behavior of the validator:
* `test_site_validation_wrong_length`
* `test_site_validation_non_number`
* `test_site_validation_not_a_tuple`
* `test_site_validation_invalid_site_type`
By submitting this pull request, I confirm that my contribution is made under the terms of the …

feature: validate site when adding to register

---

src/braket/circuits/circuit.py
src/braket/devices/device.py
src/braket/devices/local_simulator.py
test/unit_tests/braket/circuits/test_circuit.py
test/unit_tests/braket/devices/test_local_simulator.py

Support specifying inputs from `device.run` for the local simulator. A circuit with free parameters, when passed along with correct input, will run successfully on the local simulator. The AwsDevice class does not at this moment have an option for inputs added, so the behavior is unchanged.
Unit tests and manual e2e verification.

feature: support inputs in the device interface

---

setup.py

*Issue #, if available:* NA
*Description of changes:* Bump [`oqpy`](https://github.com/openqasm/oqpy) version. The [0.1.1 release](https://github.com/openqasm/oqpy/releases/tag/v0.1.1) loosens the bounds on numpy and openpulse, making it easier to use with other projects. We ran into this on [mitiq](https://github.com/unitaryfund/mitiq) since the 1.32 release of `amazon-braket-sdk` which added oqpy as a dependency.
*Testing done:* None. The changes in the latest oqpy release look small. Hoping CI should be enough, but let me know if there is other testing I should try.

bump oqpy version

---

src/braket/pulse/ast/approximation_parser.py
test/unit_tests/braket/pulse/ast/test_approximation_parser.py

N/A
We change the way the phase of frames is displayed by bounding it between 0 and 2pi.
*Testing done:* 
We add a new test that checks specifically for the case where the phase is initially set above 2pi and shifting out of the 0-2pi range.

Plot the phase between 0 and 2*pi

---

setup.py

*Issue #, if available:* NA
*Description of changes:* `oqpy` [released version 0.1.2](https://github.com/openqasm/oqpy/releases/tag/v0.1.2) which is python 3.11 compatible. We'd like to support python 3.11 over on Mitiq as well, but are blocked by the pinned version of oqpy here. I've gone ahead and removed the version specifier completely since many other dependencies are also unspecified, but let me know if having some range would be better.
*Testing done:* None

loosen oqpy requirement

---

src/braket/circuits/observables.py
src/braket/circuits/result_type.py
src/braket/circuits/result_types.py
test/unit_tests/braket/circuits/test_observable.py

Default ASCII representation of Hamiltonians (Sum observables) to "Hamiltonian".
Opt to underestimate qubit count for Sum observables rather than overestimate
unit testing, manual performance testing

fix: Hamiltonian ascii simplification

---

.github/workflows/publish-to-pypi.yml

https://github.com/pypa/gh-action-pypi-publish#-master-branch-sunset-
This changes the branch to the recommended branch. Currently the branch used is sunset.

infra: change publish to pypi wf to use release/v1

---

src/braket/circuits/__init__.py

Exports the `DoubleAngledGate` symbol, which was not accessible from outside the package. The `AngledGate` symbol was already exported, so this is for consistency.
Verified that I can access the `DoubleAngledGate` symbol from outside the package. No tests added for this change. (The `DoubleAngledGate` class already has unit tests, and I'm not sure how to test this change otherwise.)
By submitting this pull request, I confirm that my contribution is made under the …

fix: add DoubleAngledGate as exported symbol

---

src/braket/circuits/unitary_calculation.py
test/unit_tests/braket/circuits/test_circuit.py

Ignores `CompilerDirective` instructions when calculating the unitary representation for a circuit. Without this change, it is impossible to get the unitary of a circuit that contains a verbatim box. My understanding is that `CompilerDirective` instructions should never change the unitary representation of a circuit, so these are safe to ignore in this context.
Added a unit test to ensure this case works properly.
By submitting this pull request, I confirm that my …

fix: ignore CompilerDirective when calculating unitary

---

setup.cfg
setup.py
tox.ini

I got annoyed of waiting for tests to run so I wanted to do something to speed them up.
Performance tested using `time tox -e unit-tests` on main and the new branch.
Before:
```
tox -e unit-tests  94.95s user 12.11s system 62% cpu 2:50.52 total
```
After:
```
tox -e unit-tests  74.72s user 13.27s system 111% cpu 1:19.01 total
```

infra: speed up unit testing by automatically parallelizing the CPU workers for test runs

---

src/braket/parametric/free_parameter_expression.py
test/unit_tests/braket/parametric/test_free_parameter_expression.py

feat: add string support for FreeParameterExpressions

feat: add string support for FreeParameterExpressions

---

src/braket/circuits/circuit.py
test/unit_tests/braket/circuits/test_circuit.py

Gates with some floats and some free parameters now supported
Bug:
Code would check if there were *any* free parameters in the instruction and then treat *all* values as free parameters, which would break for floats
Unit and manual

fix: mixed free parameters and floats

---

setup.py
src/braket/circuits/angled_gate.py
src/braket/circuits/gates.py
test/unit_tests/braket/circuits/test_angled_gate.py
test/unit_tests/braket/circuits/test_gates.py

Add optional third angle to IonQ native MS gate.
On the service, fails due to lack of support for third angle: `botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the CreateQuantumTask operation: [line 4] invalid number of argument(s). Expected: 2, Got: 3`
Unit testing and manual testing (fails today, will repeat before merging)
By submitting this pull request, I confirm that my contribution is made under the terms of the …

feat: add optional third angle to MS gate

---

src/braket/experimental/autoqasm/__init__.py
src/braket/experimental/autoqasm/api/api.py
src/braket/experimental/autoqasm/operators/assignments.py
src/braket/experimental/autoqasm/types/py_to_oqpy.py
src/braket/experimental/autoqasm/types/types.py
test/unit_tests/braket/experimental/autoqasm/test_types.py

Increase code coverage to 100% for types modules of AutoQASM
- Remove unused code
- Add lots of tests: various parameter type annotations and various return type annotations
where various means: bit, bool, int, float, array, program.Program and some other random input to check implicit handling
- Discovered some bugs:
- bugfix for returned values that are never instantiated
- bugfix for return variables initialized with length 0 instead of matching subroutine call return size
- opened issue for bug: return constant value yields no instructions or incomplete instructions
- opened issue for bug: passing arguments directly to function call doesn't give the generated variable a name
- opened issue for bug: Array lengths are hardcoded in …

change: Increase types module coverage to 100% and fix related bugs

---

src/braket/experimental/autoqasm/README.md
src/braket/experimental/autoqasm/api/api.py
src/braket/experimental/autoqasm/errors.py
src/braket/experimental/autoqasm/program/__init__.py
src/braket/experimental/autoqasm/program/program.py
test/unit_tests/braket/experimental/autoqasm/test_api.py

*Issue #, if available:* https://github.com/orgs/amazon-braket/projects/2/views/1?pane=issue&itemId=32622428
Previous:
```
@aq.function
def my_func():
for i in aq.range(5):
cnot(i, i + 1)
prog = my_func(num_qubits=6)
```
New:
```
@aq.function(num_qubits=6)
def my_func():
for i in aq.range(5):
cnot(i, i + 1)
prog = my_func()
```
Updated unit tests

Change: update how num_qubits get supplied by autoqasm functions

---

src/braket/quantum_information/pauli_string.py
test/unit_tests/braket/quantum_information/test_pauli_string.py

* Implements half of #553 
* I was confused why the phase is only allowed to be positive or negative one, so I just assumed the convention of dropping the global phase whilst maintaining sign (e.g. `-iX` being treated as `-X`)
* Doesn't include a test case for `to_circuit()`

feat: Add dot(), power(), and to_circuit() to PauliString

---

src/braket/aws/aws_quantum_task.py
src/braket/circuits/circuit.py
test/unit_tests/braket/circuits/test_circuit.py

`to_ir` mutates calibrations because we copy it in `device.run`
moved the copy function call in `to_ir`
Added a test in an existing unit test

fix: copy calibrations in to_ir

---

.github/workflows/stale_issue.yml
test/unit_tests/braket/pulse/test_waveforms.py

The stale issue workflow is still scoped to write permissions but the top level permissions defaults to read only.
Included a minor linter fix for a waveform test.

infra: change top level permissions to read for the stale issue workflow

---

src/braket/tasks/analog_hamiltonian_simulation_quantum_task_result.py
test/unit_tests/braket/tasks/test_analog_hamiltonian_simulation_task_result.py

The results from the QPU contain additional metadata, but we weren't exposing them in our results object. With this change the additional metadata can be retrieved just like task metadata.
Tested in Gamma that I can run a task and get results back in the object. 

change: making additional meta available in AHS results

---

examples/job.py

This reverts commit 1fed55d88333d4acd2302734ee88f707ce418a12.
move Devices enum import back to top level
manually ran example successfully

fix: move import back to top level in job example

---

test/integ_tests/test_create_quantum_job.py

* Update tests for quantum jobs to remove log entries which assert a specific python version. 
* These started failing after change #644
* `tox -e integ-tests -- -s -k "test_completed_quantum_job"` and `tox -e integ-tests -- -s -k "test_failed_quantum_job"` succeeded.

fix: Update quantum job tests for latest containers

---

src/braket/experimental/autoqasm/api.py
src/braket/experimental/autoqasm/errors.py
src/braket/experimental/autoqasm/operators/assignments.py
src/braket/experimental/autoqasm/operators/conditional_expressions.py
src/braket/experimental/autoqasm/operators/control_flow.py
src/braket/experimental/autoqasm/operators/slices.py
src/braket/experimental/autoqasm/program/program.py
src/braket/experimental/autoqasm/types/__init__.py
src/braket/experimental/autoqasm/types/conversions.py
test/unit_tests/braket/experimental/autoqasm/test_api.py
test/unit_tests/braket/experimental/autoqasm/test_converters.py
test/unit_tests/braket/experimental/autoqasm/test_operators.py
test/unit_tests/braket/experimental/autoqasm/test_types.py

- [Branches/conditional expressions with variable assignment produce incorrect results
](https://github.com/orgs/amazon-braket/projects/2/views/1?pane=issue&itemId=32619400)
- For conditional expressions, the `if_exp` operator needs to return the appropriate variable object. It also needs to validate that both the `if` and `else` expressions are of the same type.
- For branches (if-else blocks), manually calling `declare()` for assignment statements caused the variable to be defined inside the if-else block. Instead, we need to allow `oqpy` to automatically declare the variable, which will put it at the correct scope. Note that for subroutines, we now must call `autodeclare()` after executing the subroutine function so that `oqpy` will …

fix: autoqasm programs with assignments inside conditionals and branches

---

.github/workflows/python-package.yml
src/braket/experimental/autoqasm/types/types.py
test/unit_tests/braket/experimental/autoqasm/test_api.py
test/unit_tests/braket/experimental/autoqasm/test_operators.py
tox.ini

- [IPE example notebook failure: "Identifier '`__bit_1__`' is not initialized."](https://github.com/orgs/amazon-braket/projects/2/views/6?pane=issue&itemId=34795314)
- Ensure that `aq.BitVar` registers always have an appropriate `init_expression`.
- Add AutoQASM example notebooks to tox and CI pipeline to prevent future failures.
- Existing tests updated.
- Added tests to run a few relevant programs on LocalSimulator to ensure that these programs are syntactically correct. Verified that these new tests would have caught this bug prior to fixing it.
- Ensure that notebook validation is working in tox and CI pipeline.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure …

fix: Ensure AutoQASM bit registers are always properly initialized

---

src/braket/experimental/autoqasm/operators/assignments.py
test/unit_tests/braket/experimental/autoqasm/test_types.py

- [incorrect assignment type check for subroutine input arg](https://github.com/orgs/amazon-braket/projects/2/views/6?pane=issue&itemId=34477183)
- Convert the types of each variable before checking the types for equality.
- Added a test for the newly-working scenario.

fix: assigning AutoQASM subroutine arg to a local variable

---

src/braket/timings/time_series.py
test/unit_tests/braket/timings/test_time_series.py

1. The TimeSeries.constant_like method is supposed to be able to take in TimeSeries as an argument, but from the implementation, it is not
2. Add a method to create trapezoidal time series
see above

fix: fix a bug in time series and add trapezoidal time series

---

src/braket/experimental/autoqasm/types/conversions.py
test/unit_tests/braket/experimental/autoqasm/test_types.py

- previous error message: `TypeError: tuple() takes no keyword arguments`
- new error message: `Tuple parameter types are not supported; please use "list" instead.`
new test

Improve error message for tuple parameters

---

src/braket/experimental/autoqasm/api.py
src/braket/experimental/autoqasm/errors.py
test/unit_tests/braket/experimental/autoqasm/test_types.py

Previously, we got a very unhelpful message if a parameter was missing a type hint, because we were mistakenly adding 
(empty) annotations to parameters that were not annotated. This prevented us from getting the nice OQPY error message, but rather than handle empty annotations (that are invalid anyway), raise our own error.

Add error for missing parameter type hints

---

src/braket/experimental/autoqasm/api.py
src/braket/experimental/autoqasm/converters/break_statements.py
src/braket/experimental/autoqasm/errors.py
src/braket/experimental/autoqasm/types/conversions.py
test/unit_tests/braket/experimental/autoqasm/test_api.py
test/unit_tests/braket/experimental/autoqasm/test_converters.py
test/unit_tests/braket/experimental/autoqasm/test_types.py

- rename `UnsupportedFeature` -> `UnsupportedFeatureError`
- Use actual return variable to set return type, except for recursive functions (task created: https://github.com/orgs/amazon-braket/projects/2/views/1?pane=issue&itemId=35482594)
- better error message if user supplies `list` instead of `list[type]` for parameter type hint
- follow up task: https://github.com/orgs/amazon-braket/projects/2/views/1?pane=issue&itemId=35482594
unit tests
By submitting this pull …

Return type hint ignored when possible in favor of actual return type

---

src/braket/experimental/autoqasm/__init__.py
src/braket/experimental/autoqasm/program/__init__.py
test/unit_tests/braket/experimental/autoqasm/test_pragmas.py

Aliasing `Verbatim()` so that it is accessible at the top level as `aq.verbatim()`.
unit tests

[autoqasm] aliasing Verbatim class

---

setup.py
src/braket/aws/aws_quantum_task_batch.py
src/braket/devices/local_simulator.py
src/braket/tasks/local_quantum_task.py
src/braket/tasks/local_quantum_task_batch.py
src/braket/tasks/quantum_task_helper.py
test/unit_tests/braket/aws/test_aws_device.py
test/unit_tests/braket/devices/test_local_simulator.py
test/unit_tests/braket/tasks/test_local_quantum_task.py
tox.ini

feat: LocalQuantumTask to use ExecutionManager

---

src/braket/circuits/circuit.py
src/braket/circuits/serialization.py
src/braket/parametric/free_parameter.py
src/braket/pulse/ast/qasm_transformer.py
test/integ_tests/test_adjoint_gradient.py
test/unit_tests/braket/aws/test_aws_quantum_task.py
test/unit_tests/braket/circuits/test_circuit.py
test/unit_tests/braket/circuits/test_gates.py
test/unit_tests/braket/circuits/test_noises.py
test/unit_tests/braket/circuits/test_observables.py
test/unit_tests/braket/circuits/test_result_types.py
test/unit_tests/braket/devices/test_local_simulator.py
test/unit_tests/braket/parametric/test_free_parameter.py

https://github.com/aws/amazon-braket-sdk-python/issues/603
When generating OpenQASM we decided to use 'b' and 'q' for 'bits' and 'qubits' variables, but this can collide with parameters chosen by customers. I've renamed these to ```__bits__``` and  ```__qubits__``` and have changed our requirements for FreeParameter names so that we exclude names that start with double underlines. I've also updated the verification function for our FreeParameter names to be closer to the identifiers definition from [OpenQASM](https://openqasm.com/language/types.html) to further reduce changes there will be transformation errors (some of which are mentioned in the ticket above).
This check is not exact, so it's possible that we'll allow for FreeParameter …

update: restricting parameter names to not collide with ones we use for OpenQASM generation.

---

examples/autoqasm/1_Getting_started_with_AutoQASM.ipynb
examples/autoqasm/2_Expressing_classical_control_flow.ipynb
examples/autoqasm/3_Iterative_phase_estimation.ipynb
src/braket/experimental/autoqasm/README.md
src/braket/experimental/autoqasm/__init__.py
src/braket/experimental/autoqasm/api.py
src/braket/experimental/autoqasm/errors.py
src/braket/experimental/autoqasm/instructions/__init__.py
src/braket/experimental/autoqasm/instructions/measurements.py
src/braket/experimental/autoqasm/program/pragmas.py
src/braket/experimental/autoqasm/pulse/__init__.py
test/unit_tests/braket/experimental/autoqasm/conftest.py
test/unit_tests/braket/experimental/autoqasm/test_api.py
test/unit_tests/braket/experimental/autoqasm/test_converters.py
test/unit_tests/braket/experimental/autoqasm/test_gate_decorator.py
test/unit_tests/braket/experimental/autoqasm/test_operators.py
test/unit_tests/braket/experimental/autoqasm/test_pragmas.py
test/unit_tests/braket/experimental/autoqasm/test_program.py
test/unit_tests/braket/experimental/autoqasm/test_pulse.py
test/unit_tests/braket/experimental/autoqasm/test_transpiler.py
test/unit_tests/braket/experimental/autoqasm/test_types.py

https://github.com/orgs/amazon-braket/projects/2/views/1?pane=issue&itemId=35858838
Split `aq.function` into `aq.main` and `aq.subroutine`.
I am planning to do a follow up PR to refactor api.py
input
```
@aq.subroutine
def bell(q0: int, q1: int):
h(q0)
cnot(q0, q1)
@aq.subroutine
def ghz_n(n: int):
if n < 2:
return
for i in aq.range(n - 1):
bell(i, i + 1)
@aq.main(num_qubits=6)
def main():
ghz_n(6)
```
generated code
```
OPENQASM 3.0;
def bell(int[32] q0, int[32] q1) {
h __qubits__[q0];
cnot __qubits__[q0], __qubits__[q1];
}
def ghz_n(int[32] n) {
if (n < 2) {
} else {
for int i in [0:n - 1 - 1] {
bell(i, i + 1);
}
}
}
qubit[6] __qubits__;
ghz_n(6);
```
**What's allowed at the global scope is not the same as what is allowed within a `subroutine`:** …

Split aq.function into aq.main and aq.subroutine

---

src/braket/experimental/autoqasm/api.py
src/braket/experimental/autoqasm/program/program.py

Doing an AutoQASM `api.py` refactor. Making this as a first, small PR, because it is separable, and a gitdiff with indentation changes and other changes can be confusing.
There are NO code changes beyond de-dentation and moving code
Source: https://vaclavkosar.com/software/Python-Context-Manager-With-Statement-Exception-Handling

Move error handling into the context manager

---

src/braket/experimental/autoqasm/api.py

Refactor api.py part 2
- Was able to consolidate duplicated code through a callback function
- Minus 100 LOC!
- Also discovered that NullContext doesn't have any affect (used in place of optional context managers: https://docs.python.org/3/library/contextlib.html)
The diff is a bit confusing, so here's a more detailed description:
- There are three decorators: `main`, `subroutine` and `gate`. Each call `_function_wrapper`
- There are three decorator converters: `_convert_main`, `_convert_subroutine` and `_convert_gate`
- `_convert_program_wrapper` and `_convert_gate_wrapper` are merged into `_function_wrapper`
- `_function_wrapper` accepts a callback, which is one of the `_convert_X` functions
- `_convert_program` is deleted, and its code is subsumed into `_convert_main` and/or …

Use a callback to simplify autoqasm/api logic

---

setup.cfg
test/unit_tests/braket/pulse/test_pulse_sequence.py

This will allow for users to see tests taking a long time. In this context, long is set to 1 second but that value can be reduced or increased using the parameter `--durations-min` within `setup.cfg`.
The pytest port was reduced as [test_pulse_sequence_to_time_trace_program_mutation](https://github.com/aws/amazon-braket-sdk-python/blob/main/test/unit_tests/braket/pulse/test_pulse_sequence.py#L273) is taking considerably longer than other tests. The main driving factor in the increased time is writing to 3 dictionaries 1,000,000 times. From the profiling done:
```
6002791 function calls (6002209 primitive calls) in 8.160 seconds
...
3000000    5.880    0.000    6.715    0.000 time_series.py:42(put)
```
This is done in the …

test: speed up pulse time trace and add test timing outputs

---

src/braket/experimental/autoqasm/__init__.py
src/braket/experimental/autoqasm/api.py
src/braket/experimental/autoqasm/errors.py
src/braket/experimental/autoqasm/instructions/qubits.py
src/braket/experimental/autoqasm/program/gate_calibrations.py
src/braket/experimental/autoqasm/program/program.py
src/braket/experimental/autoqasm/pulse/pulse.py
test/unit_tests/braket/experimental/autoqasm/test_api.py
test/unit_tests/braket/experimental/autoqasm/test_gate_calibrations.py
test/unit_tests/braket/experimental/autoqasm/test_pulse.py

https://github.com/orgs/amazon-braket/projects/2/views/6?pane=issue&itemId=35379372
- Implement `@aq.gate_calibration` decorator
- The decorator takes an `implements` kwargs`, acting as a defcal. The body of defcal can only have pulse operations
- Users can attach gate calibrations to a main program with `my_program.with_calibrations([cal_1, cal_2])`. The attachment returns new program object and does not modify the original program.
*Example* 
```
@aq.gate_calibration(implements=rx, target="$1")
def cal_1(angle: float):
pulse.delay(1, angle)
@aq.main
def my_program():
rx("$1", 1.0)
prog = my_program()
prog.bind_calibrations([cal_1])
```
*Note:*
Support of variable qubit is low. Currently, qubits for defcal can be passed as a fixed value …

feat: gate calibrations that bind to built main programs

---

.github/workflows/check-format.yml
.github/workflows/python-package.yml
examples/autoqasm/4_Native_programming.ipynb
examples/autoqasm/ionq_gates.py
src/braket/experimental/autoqasm/api.py
src/braket/experimental/autoqasm/errors.py
src/braket/experimental/autoqasm/instructions/instructions.py
src/braket/experimental/autoqasm/instructions/qubits.py
src/braket/experimental/autoqasm/program/__init__.py
src/braket/experimental/autoqasm/program/pragmas.py
src/braket/experimental/autoqasm/program/program.py
src/braket/experimental/autoqasm/pulse/pulse.py
test/unit_tests/braket/experimental/autoqasm/test_devices.py
test/unit_tests/braket/experimental/autoqasm/test_pragmas.py
tox.ini

- [Validation against device capabilities](https://github.com/orgs/amazon-braket/projects/2/views/1?pane=issue&itemId=35380241)
- [User story: Native programming customer mini-journey with device-specific validation
](https://github.com/orgs/amazon-braket/projects/2/views/1?pane=issue&itemId=32620015)
- Validate that all gates used are in the `supportedOperations` of the device properties.
- Validate that verbatim blocks contain only native gates of the target device.
- Validate that verbatim blocks reference only physical qubits.
- Validate that verbatim blocks respect the connectivity of the target device.
- Example notebook added with user scenario of custom native gate definitions and verbatim usage.
- Tests added to …

feature: device-specific gate validation for autoqasm programs

---

src/braket/experimental/autoqasm/api.py
test/unit_tests/braket/experimental/autoqasm/test_api.py

- [Bit register returned from subroutine is assigned to single bit variable](https://github.com/orgs/amazon-braket/projects/2/views/6?pane=issue&itemId=36846211)
- Initialize the `aq.BitVar` return instance with the correct size based on the return value of the subroutine.
- Test updated to account for fixed behavior.

fix: Return correctly-sized bit register from AutoQASM subroutine

---

src/braket/experimental/autoqasm/README.md
src/braket/experimental/autoqasm/doc/decorators.md

Add decorator documentation, link from README

Add documentation about decorators

---

examples/job.py
src/braket/jobs/__init__.py
src/braket/jobs/data_persistence.py
src/braket/jobs/environment_variables.py
test/integ_tests/job_test_script.py
test/unit_tests/braket/jobs/test_environment_variables.py

Add some helpers functions for use inside of hybrid jobs
unit, integ, manual

feat: job helper functions

---

src/braket/jobs/hybrid_job.py
test/unit_tests/braket/jobs/test_data_persistence.py

Assert circular import is resolved and update pending docs
unit tests

fix: address todos

---

src/braket/jobs/hybrid_job.py
test/unit_tests/braket/jobs/test_hybrid_job.py

add unit tests to cover missed lines of code
unit tests

test: add full coverage

---

src/braket/jobs/_entry_point_template.py

import missing fix
manual verification + unit/integ

fix: input data import in template

---

src/braket/aws/aws_quantum_job.py
src/braket/jobs/config.py
src/braket/jobs/data_persistence.py
src/braket/jobs/environment_variables.py
src/braket/jobs/hybrid_job.py
src/braket/jobs/local/local_job.py
src/braket/jobs/quantum_job_creation.py

update typing and misc to utilize 3.9
unit tests and a bit of manual verification

feat: update to 3.9 syntax

---

src/braket/jobs/hybrid_job.py
test/integ_tests/test_create_quantum_job.py
test/unit_tests/braket/jobs/test_hybrid_job.py

shorten long strings and replace forbidden chars with `?`
unit and manual testing

feat: sanitize hp strings

---

src/braket/jobs/hybrid_job.py

Don't instantiate aws_session in the decorator
notebook testing passing from this fix, unit tests

fix: use separate aws session for python validation

---

tox.ini

Currently, we are running over the `src` directory twice for our linters. The BCS plugin only needs to run over the `src` directory so this will alleviate the amount of times this is ran.
```
tox -e linters
...
linters run-test: commands[0] | isort .
Skipped 3 files
linters run-test: commands[1] | black ./
All done! ✨ 🍰 ✨
235 files left unchanged.
linters run-test: commands[2] | flake8 --extend-exclude src
linters run-test: commands[3] | flake8 --enable-extensions=BCS src
src/braket/circuits/circuit.py:77:101: E501 line too long (175 > 100 characters)
```
From benchmarking, average runtime before was around 23 seconds and this brings it down to 15 seconds.
_Put an `x` in the boxes that apply. You can also fill these out …

infra: stop flake8 running over the src directory twice

---

test/integ_tests/test_create_quantum_job.py

xfail unsupported python versions
Ran integ tests from 3.9 and saw 
```
[gw1] [ 50%] XFAIL test/integ_tests/test_create_quantum_job.py::test_decorator_job_submodule 
[gw0] [100%] XFAIL test/integ_tests/test_create_quantum_job.py::test_decorator_job 
```
Manually verified integ tests FAIL if the test either succeeds or raises an incorrect type of error

test: pytest skip python version mismatch

---

src/braket/experimental/autoqasm/api.py
src/braket/experimental/autoqasm/instructions/instructions.py
src/braket/experimental/autoqasm/instructions/measurements.py
src/braket/experimental/autoqasm/instructions/qubits.py
src/braket/experimental/autoqasm/operators/conditional_expressions.py
src/braket/experimental/autoqasm/operators/control_flow.py
src/braket/experimental/autoqasm/program/gate_calibrations.py
src/braket/experimental/autoqasm/program/program.py
src/braket/experimental/autoqasm/pulse/pulse.py
src/braket/experimental/autoqasm/transpiler/transpiler.py
src/braket/experimental/autoqasm/types/types.py
test/unit_tests/braket/experimental/autoqasm/conftest.py
test/unit_tests/braket/experimental/autoqasm/mock_transpiler.py
test/unit_tests/braket/experimental/autoqasm/test_operators.py
test/unit_tests/braket/experimental/autoqasm/test_types.py

*Issue #, if available:* Closes #754
Update type hints to use built-ins rather than `typing`. This is recommended for Python 3.9+.
This also allows us to remove a bit of code from `api.py` which was handling these different inputs, as AutoQASM needs to inspect type hints.
no new functionality, updates handled by existing tests.

Update type hints

---

src/braket/devices/local_simulator.py
src/braket/experimental/autoqasm/api.py
src/braket/experimental/autoqasm/instructions/gates.py
src/braket/experimental/autoqasm/instructions/instructions.py
src/braket/experimental/autoqasm/program/program.py
test/unit_tests/braket/experimental/autoqasm/test_parameters.py

Part 1 of #757
This allows statements such as `rx(0, FreeParameter("theta"))` in AutoQASM programs.
When converted to OpenQASM, the resulting program has an input statement, such as `input float[32] theta;`.
This PR will be followed by these additional works to complete the feature:
1. Support expressions of parameters
2. Support other types besides float
3. Support free parameters in conditional statements
4. Documentation -- when the feature is more complete
New test file!
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull …

[feature] AutoQASM: Free parameters

---

test/unit_tests/braket/experimental/autoqasm/test_parameters.py

Thank you @yitchen-tim and @rmshaffer for catching my mistake!

bug: Fixup numerical imprecision

---

test/integ_tests/job_test_script.py
test/integ_tests/test_create_quantum_job.py

Update failed quantum job test with improved error message
Integ test passing

test: update failed job integ test

---

src/braket/experimental/autoqasm/instructions/qubits.py
src/braket/experimental/autoqasm/pulse/pulse.py

- Support the `Qubit` and `QubitSet` types from the `braket.registers` module.
- Additional minor cleanup.
- `tox` passes.

[fix] Update AutoQASM to consume qubit types from braket.registers module

---

src/braket/jobs/_entry_point_template.py

Move cd to set working directory at run time rather than import time. Important because container sets its own working directory between the two.
Manual verification, regression testing

fix: set decorator job working directory inside of function

---

test/integ_tests/test_create_quantum_job.py

Previous set up was skipping even when version matched
integ test passing with correct python version and skipping with incorrect

fix: set python container version explicitly

---

src/braket/jobs/hybrid_job.py

Use the standard approach for creating a partial function instead of building our own.
unit/integ tests passing

feat: simplify entry point wrapper

---

src/braket/jobs/quantum_job_creation.py

This change will make a call to invalidate the internal caches in importlib when using decorator jobs. From [imprortlib docs](https://docs.python.org/3/library/importlib.html#importlib.invalidate_caches),
> This function should be called if any modules are created/installed while your program is running to guarantee all finders will notice the new module’s existence.
This is the situation when the hybrid job decorator creates a new source module to create a new job while the program is running.
* local unit & integ tests
* https://github.com/amazon-braket/amazon-braket-examples/pull/447
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate …

Fix: Invalidate importlib cache for decorator job

---

src/braket/experimental/autoqasm/api.py
src/braket/experimental/autoqasm/program/program.py
test/unit_tests/braket/experimental/autoqasm/test_parameters.py

Closes #769 
Support `make_bound_program`
```
@aq.main
def my_circuit(main_argument: float):
free_param = FreeParameter("alpha")
rx(0, main_argument)
rx(1, free_param)
measure([0, 1])
my_circuit(3.14/2).make_bound_program({"alpha": 3.14}).to_ir()
```
The name and signature is patterned after `make_bound_circuit`. This name also helps inform the user that the method will make and return a new object, with the original left unchanged.
```
def make_bound_program(self, param_values: dict[str, float]) -> Program:
def make_bound_circuit(self, param_values: dict[str, Number], strict: bool = False) -> Circuit:
```
New unit tests
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're …

feature: support FreeParameter binding via `make_bound_program`

---

src/braket/circuits/circuit.py

*Issue #, if available:* N/A
Minor docstring improvement inspired by https://github.com/amazon-braket/amazon-braket-sdk-python/pull/779

documentation: Improve docstring for make_bound_circuit

---

src/braket/experimental/autoqasm/instructions/measurements.py
test/unit_tests/braket/experimental/autoqasm/test_api.py

- A change in #763 broke AutoQASM measurement of physical qubits, and we had no test to check for this.
- Change the parameter type check in `measure` so that we handle physical qubits (i.e., strings) correctly.
- Add a test for physical qubit measurement. Also verify that `tox -e notebooks` passes locally.

fix: AutoQASM measurement of physical qubits

---

src/braket/tasks/gate_model_quantum_task_result.py
test/unit_tests/braket/tasks/test_gate_model_quantum_task_result.py

Add `get_compiled_circuit` to GateModelQuantumTaskResult
Closes #780 
Proposed method:
```
compiled_program = task.result().get_compiled_program()
```
For Rigetti and OQC tasks, this could be used instead of the method described here: https://docs.aws.amazon.com/braket/latest/developerguide/braket-compiled-circuits-inspecting.html
New unit tests, local testing with successful quantum tasks ran on hardware
By submitting this pull request, I confirm that my …

feature: Add get_compiled_circuit convenience method

---

src/braket/experimental/autoqasm/converters/comparisons.py
src/braket/experimental/autoqasm/errors.py
src/braket/experimental/autoqasm/operators/__init__.py
src/braket/experimental/autoqasm/operators/comparisons.py
src/braket/experimental/autoqasm/operators/logical.py
src/braket/experimental/autoqasm/operators/utils.py
src/braket/experimental/autoqasm/program/program.py
src/braket/experimental/autoqasm/transpiler/transpiler.py
src/braket/experimental/autoqasm/types/types.py
test/unit_tests/braket/experimental/autoqasm/test_api.py
test/unit_tests/braket/experimental/autoqasm/test_operators.py
test/unit_tests/braket/experimental/autoqasm/test_parameters.py
test/unit_tests/braket/experimental/autoqasm/test_program.py
test/unit_tests/braket/experimental/autoqasm/test_types.py

Closes #785 
This is a follow up from https://github.com/amazon-braket/amazon-braket-sdk-python/issues/757
This adds support for FreeParameters in conditional statements. For example:
```
@aq.main
def parametric(val: float | FreeParameter):
threshold = 0.9
if val > threshold:
x(0)
measure(0)
parametric(FreeParameter("val"))
```
*Details*
- New `ComparisonTransformer` to replace comparison operators with functions that we can later process ourselves
- Comparison operator processing for <, <=, >, >=
- arguments processed by `autoqasm/operators/` (both logical and comparison stmts) now check for FreeParameters. If found, they're registered with the program conversion context and converted to the newly associated FloatVar
- Minor API cleanup …

feature: Add support for FreeParameters in AutoQASM conditional statements

---

src/braket/experimental/autoqasm/pulse/pulse.py
test/unit_tests/braket/experimental/autoqasm/test_pulse.py

https://github.com/orgs/amazon-braket/projects/2/views/6?pane=issue&itemId=44479389
- Register the pulse usage of free parameter in program. 
- Enable binding value to free parameter for pulse instructions.
tox

AutoQASM freeparameter usage with pulse instruction

---

src/braket/experimental/autoqasm/operators/utils.py
src/braket/experimental/autoqasm/program/program.py
test/unit_tests/braket/experimental/autoqasm/test_parameters.py
test/unit_tests/braket/experimental/autoqasm/test_program.py

[AutoQASM: support for FreeParameterExpressions](https://github.com/orgs/amazon-braket/projects/2/views/1?pane=issue&itemId=43127738)
Support `FreeParameterExpression` objects as inputs to AutoQASM programs and subroutines, in addition to `FreeParameter` objects.
Unit tests added. tox passes.

feat: Support FreeParameter expressions in AutoQASM programs

---

src/braket/aws/aws_device.py
src/braket/aws/aws_session.py
test/integ_tests/test_device_creation.py
test/unit_tests/braket/aws/test_aws_session.py

update: default no longer returning RETIRED devices from get_devices

---

test/unit_tests/braket/test_imports.py

I reset back to where we had the issue with https://github.com/amazon-braket/amazon-braket-sdk-python/commit/eed59ff40e59075c2ffca7a03ac2db7730892506 change, and then verified that I could detect the issue regardless of the order that the modules were tested in.

update: adding a test to check for circular imports

---

src/braket/circuits/basis_state.py
test/unit_tests/braket/circuits/test_basis_state.py

Add a few convenience methods to the BasisState class
Manual and unit testing

feat: add str, repr and getitem to BasisState

---

src/braket/experimental/autoqasm/__init__.py
src/braket/experimental/autoqasm/api.py
src/braket/experimental/autoqasm/program/pragmas.py
src/braket/experimental/autoqasm/program/program.py
src/braket/experimental/autoqasm/types/__init__.py
src/braket/experimental/autoqasm/types/types.py
test/unit_tests/braket/experimental/autoqasm/test_annotations.py
test/unit_tests/braket/experimental/autoqasm/test_operators.py
test/unit_tests/braket/experimental/autoqasm/test_types.py

Resolves #837 
Support `annotations` argument for subroutines, variables, ranges, and boxes. This will result in an OpenQASM annotation being added to the serialized program.
For example:
```
@aq.subroutine(annotations=["inline"])
def subroutine_test():
pass
@aq.main
def main():
subroutine_test()
```
produces:
```
OPENQASM 3.0;
@inline
def subroutine_test() {
}
subroutine_test();
```
Tests added to verify new functionality. tox passes.
By submitting this pull …

feature: Support OpenQASM annotations in AutoQASM programs

---

src/braket/aws/aws_quantum_job.py
src/braket/aws/aws_quantum_task.py
src/braket/jobs/hybrid_job.py
src/braket/jobs/logs.py
test/unit_tests/braket/aws/test_aws_quantum_job.py
test/unit_tests/braket/aws/test_aws_quantum_task.py

feat: add queue position to the logs for tasks and jobs

---

src/braket/aws/aws_quantum_task_batch.py

`repeat()` is unbounded unless `times` is set. This sets it to the max of the list of inputs or task specifications.

fix: update batch circuit to limit repeat calls

---

src/braket/experimental/autoqasm/errors.py
src/braket/experimental/autoqasm/operators/assignments.py
src/braket/experimental/autoqasm/operators/return_statements.py
src/braket/experimental/autoqasm/program/program.py
src/braket/experimental/autoqasm/types/conversions.py
src/braket/experimental/autoqasm/types/types.py
test/unit_tests/braket/experimental/autoqasm/test_api.py
test/unit_tests/braket/experimental/autoqasm/test_return.py

*Issue #, if available:* #875
Follow up on `return` statement support from AutoQASM `main` decorated functions
- Name conflict error is raised rather than name mangling when input and output names are the same. New `NameConflict` error
- Clean up output registration between `return_statements` and `program`
- Simplify wordy parameter names for `register_input/output_parameter`. For example, `parameter_name` -> `name`
- Fix issue where output `bit`s did not have the right size
- Fix issue in `aq.types` where `"output"` init expression is overwritten for `BitVar`s
Follow ups after this:
- returning tuples
- more complicated expressions within control flow
- a couple more lines need test coverage
new unit tests
_Put an `x` in the boxes that apply. …

feature: Follow up with AutoQASM return statement fixes

---

src/braket/experimental/autoqasm/operators/assignments.py
src/braket/experimental/autoqasm/operators/return_statements.py
src/braket/experimental/autoqasm/types/conversions.py
test/unit_tests/braket/experimental/autoqasm/test_return.py

*Issue #, if available:* #875
Support returning tuples, e.g.
```
@aq.main
def main():
return measure(0), True, 1.23
```
New unit tests

feature: Add support for returning tuples of values from aq.main

---

test/integ_tests/test_reservation_arn.py

Removing this test and this should be part of backend testing and we shouldn't be creating jobs with QPUs.
tox

fix: remove job creation test with qpu

---

test/unit_tests/braket/experimental/autoqasm/test_return.py

Bug report: https://github.com/orgs/amazon-braket/projects/2/views/1?filterQuery=bug&pane=issue&itemId=54041940
This test was added for testing `return` statements for AutoQASM, but the bug pre-dates this feature. There are other situations where this bug also appears, as described in the bug report linked above. I propose removing the xfail test in favor of the bug being tracked as usual with the other issues on the AutoQASM board.
By submitting this pull request, I …

Remove xfail test that has new bug report

---

src/braket/experimental/autoqasm/pulse/pulse.py
test/unit_tests/braket/experimental/autoqasm/test_return.py

*Issue #, if available:* #875
Support AutoQASM return statements for `pulse.capture_v0` instruction
Example:
```
@aq.main
def program():
return capture_v0(frame)
```
New unit test

feature: Support AutoQASM return statements for pulse

---

examples/autoqasm/1_Getting_started_with_AutoQASM.ipynb
examples/autoqasm/2_Expressing_classical_control_flow.ipynb
examples/autoqasm/4_Native_programming.ipynb
examples/autoqasm/5_Pulse_programming_and_dynamical_decoupling.ipynb
examples/autoqasm/6_Customize_gate_calibrations.ipynb
src/braket/aws/aws_quantum_task.py
src/braket/circuits/serialization.py
src/braket/experimental/autoqasm/README.md
src/braket/experimental/autoqasm/__init__.py
src/braket/experimental/autoqasm/doc/decorators.md
src/braket/experimental/autoqasm/program/program.py
test/unit_tests/braket/experimental/autoqasm/test_annotations.py
test/unit_tests/braket/experimental/autoqasm/test_api.py
test/unit_tests/braket/experimental/autoqasm/test_devices.py
test/unit_tests/braket/experimental/autoqasm/test_gate_calibrations.py
test/unit_tests/braket/experimental/autoqasm/test_gate_decorator.py
test/unit_tests/braket/experimental/autoqasm/test_gate_definitions.py
test/unit_tests/braket/experimental/autoqasm/test_operators.py
test/unit_tests/braket/experimental/autoqasm/test_parameters.py
test/unit_tests/braket/experimental/autoqasm/test_pragmas.py
test/unit_tests/braket/experimental/autoqasm/test_program.py
test/unit_tests/braket/experimental/autoqasm/test_pulse.py
test/unit_tests/braket/experimental/autoqasm/test_return.py
test/unit_tests/braket/experimental/autoqasm/test_serialization_config.py
test/unit_tests/braket/experimental/autoqasm/test_transpiler.py
test/unit_tests/braket/experimental/autoqasm/test_types.py

Follow-up from #841 with mechanical changes needed to change `allow_implicit_build` default to `False`.
The vast majority of the changes are converting lines like `program.to_ir()` to `program.build().to_ir()`.
`tox` passes locally, including `tox -e notebooks`.

feat: Change AutoQASM allow_implicit_build default to False

---

test/integ_tests/gate_model_device_testing_utils.py

I'm doubling the tol value for our tests. The performance should be tuned and maintained on the backend - not as part of our github integ tests.

fix: increase tol value for our integ tests

---

test/unit_tests/braket/jobs/test_hybrid_job.py

Not specifying the protocol for `ssl.SSLContext` is deprecated.
`tox -e unit-tests`

test: add in the protocol for the ssl context

---

src/braket/experimental/autoqasm/api.py
src/braket/experimental/autoqasm/errors.py
src/braket/experimental/autoqasm/operators/comparisons.py
src/braket/experimental/autoqasm/operators/conditional_expressions.py
src/braket/experimental/autoqasm/operators/control_flow.py
src/braket/experimental/autoqasm/operators/data_structures.py
src/braket/experimental/autoqasm/operators/logical.py
src/braket/experimental/autoqasm/operators/utils.py
src/braket/experimental/autoqasm/program/pragmas.py
src/braket/experimental/autoqasm/program/program.py
src/braket/experimental/autoqasm/program/serialization_properties.py
src/braket/experimental/autoqasm/pulse/pulse.py
src/braket/experimental/autoqasm/transpiler/transpiler.py
src/braket/experimental/autoqasm/types/conversions.py
src/braket/experimental/autoqasm/types/types.py

[Convert all AutoQASM code to use new-style Python annotations (via `from __future__ import annotations`)
](https://github.com/orgs/amazon-braket/projects/2/views/1?pane=issue&itemId=57874367)
Replace usage of `Optional` and `Union` in type hints with the more modern syntax.
`tox` passes.

change: Replace usage of Optional and Union in AutoQASM type hints

---

src/braket/experimental/autoqasm/operators/assignments.py
src/braket/experimental/autoqasm/program/program.py
test/unit_tests/braket/experimental/autoqasm/test_api.py
test/unit_tests/braket/experimental/autoqasm/test_converters.py
test/unit_tests/braket/experimental/autoqasm/test_operators.py
test/unit_tests/braket/experimental/autoqasm/test_parameters.py
test/unit_tests/braket/experimental/autoqasm/test_types.py

https://github.com/amazon-braket/amazon-braket-sdk-python/issues/929, https://github.com/amazon-braket/amazon-braket-sdk-python/issues/933
Ensure that AutoQASM variables which are updated after declaration, including iteratively in a loop, are initialized properly.
Added tests for new cases. Updated existing tests where variable declaration order changed. `tox` passes.
*Note:*
If a variable is initialized with a Python variable and then updated iteratively in a loop, this scenario still does not work with the changes in this PR. A new issue has been added to the backlog for this: https://github.com/orgs/amazon-braket/projects/2/views/1?pane=issue&itemId=58435320.
_Put an `x` in the boxes that apply. You can also fill these …

fix: iterative variable assignments in AutoQASM

---

src/braket/circuits/circuit.py
test/unit_tests/braket/circuits/test_circuit.py

Currently, the following circuits are allowed where a qubit appears to be measured more than once:
```
circ = Circuit().h(0).cnot(0, 1).rx(0, 0.9).ry(1, 0.2).measure([0,0,0,0])
circ = Circuit().h(0).cnot(0, 1).measure([1]).measure([0,1])
```
A qubit can only be measured once so we should raise an error for repeated qubits in a measure instruction.
`tox` and `tox -e integ-tests`
By submitting this pull request, I confirm that my contribution is made under the terms of …

fix: prevent repeated measurements on a qubit

---

src/braket/experimental/autoqasm/operators/assignments.py
src/braket/experimental/autoqasm/program/program.py
test/unit_tests/braket/experimental/autoqasm/test_api.py
test/unit_tests/braket/experimental/autoqasm/test_converters.py
test/unit_tests/braket/experimental/autoqasm/test_operators.py
test/unit_tests/braket/experimental/autoqasm/test_parameters.py
test/unit_tests/braket/experimental/autoqasm/test_types.py

See comment here: https://github.com/amazon-braket/amazon-braket-sdk-python/pull/930#discussion_r1550003912
Instead of deferring the variable declaration until the end, we continue to declare the variable at the time of assignment and then remove the declaration if it is no longer needed (i.e., when the variable is being used as `output`).
`tox` passes.

fix: address AutoQASM variable declaration bug introduced by PR #930

---

src/braket/circuits/braket_program_context.py
test/unit_tests/braket/circuits/test_circuit.py

Currently, the statement `b = measure q` in an OpenQASM program results in the following error:
`ValueError: Operator qubit count 1 must be equal to size of target qubit set QubitSet([Qubit(0), Qubit(1)])`
This is because a `measure` instruction is always a 1 qubit instruction but right now, [all the targets get added](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/src/braket/circuits/braket_program_context.py#L170) to the measure instruction even if there are more than 1 qubit measured. 
To reproduce this issue:
```
bell_qasm = """
OPENQASM 3;
qubit[2] q;
bit[2] c;
h q[0];
cnot q[0], q[1];
c = measure q;
"""
from braket.circuits import Circuit
print(Circuit.from_ir(bell_qasm))
```
- Add a loop to add a single measure …

fix: Support single-register measurements in `from_ir`

---

doc/conf.py
setup.py
src/braket/devices/local_simulator.py

`pkg_resources` is deprecated since setuptools > 67.5.  Import in `src/braket/devices/local_simulator.py` would cause the following warning
```
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```
It might be good to replace `pkg_resources` with other Python built-in modules, like `importlib.metadata`.

fix: Replace pkg_resources with importlib.metadata

---

src/braket/circuits/gates.py

LaTeX rendering is incorrect for gphase unitary matrix definition.
see: https://amazon-braket-sdk-python.readthedocs.io/en/latest/_apidoc/braket.circuits.gates.html#braket.circuits.gates.GPhase
Fix LaTeX markup. Also add full matrix definition for consistency with other gates. With these changes, it looks like:
Validated rendered docs from PR output.

doc: Improve gphase unitary matrix definition in docstring

---

src/braket/circuits/braket_program_context.py
test/unit_tests/braket/circuits/test_circuit.py

Currently, when a measure instruction is added in `braket_program_context.py` it is not added to the circuit's `measure_targets` which results in measure instructions getting added twice. 
*Changes made*
- `addMeasure` will now add the qubit targets to the Circuit's `measure_targets`
- updated the round trip test to properly check that the OpenQASM ir gets translated correctly
To reproduce the issue this solves:
```
qasm = """
OPENQASM 3.0;
def ghz(int[32] n) {
h q[0];
for int i in [0:n - 1] {
cnot q[i], q[i + 1];
}
}
int[32] n = 5;
bit[n + 1] c;
qubit[n + 1] q;
ghz(n);
c = measure q;
"""
circuit = Circuit.from_ir(qasm)
print(sv1.run(circuit, shots=1000).result().measurement_counts)
```
returns a ValidationException: `An error occurred …

fix: add measure qubit targets in braket_program_context

---

setup.py
src/braket/ahs/__init__.py
src/braket/ahs/analog_hamiltonian_simulation.py
test/unit_tests/braket/ahs/test_analog_hamiltonian_simulation.py
test/unit_tests/braket/ahs/test_local_detuning.py
test/unit_tests/braket/tasks/test_analog_hamiltonian_simulation_task_result.py

fix: remove shifting field from testing

---

src/braket/circuits/gates.py

Fixing a documentation mistake in #944.
Represent global phase as a 1x1 matrix rather than 2x2.
Verifying rendered docs for PR.

doc: correct gphase matrix representation

---

src/braket/ahs/driving_field.py
src/braket/ahs/field.py
src/braket/ahs/local_detuning.py
src/braket/ahs/pattern.py
src/braket/timings/time_series.py
test/unit_tests/braket/ahs/test_field.py
test/unit_tests/braket/ahs/test_pattern.py
test/unit_tests/braket/timings/test_time_series.py

fix: discretize method now takes None as an arg

---

CHANGELOG.md
doc/examples-adv-circuits-algorithms.rst
doc/examples-braket-features.rst
src/braket/annealing/problem.py
src/braket/aws/aws_device.py
src/braket/aws/aws_quantum_task.py
src/braket/aws/aws_quantum_task_batch.py
src/braket/aws/aws_session.py
src/braket/circuits/circuit.py
src/braket/circuits/gate_calibrations.py
src/braket/circuits/moments.py
src/braket/circuits/noise.py
src/braket/circuits/noise_helpers.py
src/braket/circuits/noise_model/qubit_initialization_criteria.py
src/braket/circuits/quantum_operator_helpers.py
src/braket/circuits/text_diagram_builders/ascii_circuit_diagram.py
src/braket/circuits/text_diagram_builders/text_circuit_diagram.py
src/braket/circuits/text_diagram_builders/unicode_circuit_diagram.py
src/braket/jobs/local/local_job_container.py
src/braket/tasks/analog_hamiltonian_simulation_quantum_task_result.py
src/braket/timings/time_series.py
src/braket/tracking/tracker.py

just fixing some spelling in docstrings

doc: Correct miscellaneous spelling mistakes in docstrings

---

src/braket/ahs/local_detuning.py
test/unit_tests/braket/ahs/test_analog_hamiltonian_simulation.py
test/unit_tests/braket/ahs/test_local_detuning.py

```
pip install git+https://github.com/amazon-braket/amazon-braket-sdk-python.git@fix_disc
```
```
pip freeze | grep amazon-braket                                                                                                                             
amazon-braket-default-simulator==1.21.6
amazon-braket-schemas==1.21.4
amazon-braket-sdk @ git+https://github.com/amazon-braket/amazon-braket-sdk-python.git@a196dcf0ead48aee5e6f03d987f4ab10c48733b0
```
Saved the [example for MWT](https://github.com/amazon-braket/amazon-braket-examples/blob/7a2990eef84f3dc447cda7da133cf5cc6319e6f8/examples/analog_hamiltonian_simulation/07_Maximum_Weight_Independent_Set.ipynb) as quera_program.py and ran:
```
python -m quera_program
>>> …
```

fix: remove unused discretization fields

---

src/braket/experimental/autoqasm/errors.py
src/braket/experimental/autoqasm/program/program.py
src/braket/experimental/autoqasm/transpiler/transpiler.py
test/unit_tests/braket/experimental/autoqasm/test_api.py

#809 
Raise a `NestedMainProgramError` if the user attempts to build an AutoQASM program from within the context of another AutoQASM program.
`tox` passes. Test previously marked `xfail` is now passing.

feat: Raise an error when an AutoQASM program is nested inside another program

---

src/braket/ahs/analog_hamiltonian_simulation.py
src/braket/ahs/field.py
test/unit_tests/braket/ahs/test_analog_hamiltonian_simulation.py
test/unit_tests/braket/ahs/test_field.py

- #971
- `braket.ahs.AnalogHamiltonianSimulation.from_ir()` was implemented.
Input:
```python
from braket.timings.time_series import TimeSeries
from braket.ahs.analog_hamiltonian_simulation import AnalogHamiltonianSimulation
from braket.ahs.atom_arrangement import AtomArrangement
from braket.ahs.atom_arrangement import SiteType
from braket.ahs.driving_field import DrivingField
from braket.ahs.local_detuning import LocalDetuning
from braket.ahs.field import Field
from braket.ahs.pattern import Pattern
register = (
AtomArrangement()
.add((0.0, 0.0))
.add((0.0, 3.0e-6))
.add((0.0, 6.0e-6))
.add((3.0e-6, 0.0))
.add((3.0e-6, 3.0e-6))
.add((3.0e-6, 3.0e-6), SiteType.VACANT)
.add((3.0e-6, 6.0e-6), SiteType.VACANT)
)
driving_field …
```

Implement `braket.ahs.AnalogHamiltonianSimulation.from_ir()`

---

src/braket/parametric/free_parameter.py
test/unit_tests/braket/circuits/test_ascii_circuit_diagram.py
test/unit_tests/braket/circuits/test_gates.py
test/unit_tests/braket/circuits/test_noises.py
test/unit_tests/braket/circuits/test_unicode_circuit_diagram.py
test/unit_tests/braket/parametric/test_free_parameter.py
test/unit_tests/braket/parametric/test_free_parameter_expression.py
test/unit_tests/braket/pulse/test_pulse_sequence.py

*Issue:* Fixes #603 
- The choice of name in `FreeParameter` is restricted now. Any _**SDK predefined variables**_ or _**OpenQasm reserved identifiers**_ cannot be used to as names of `FreeParameter`.
- OpenQasm reserved identifiers are picked from the grammar documentation of [OpenQasm](https://github.com/openqasm/openqasm/blob/main/source/grammar/qasm3Lexer.g4) and [OpenPulse](https://github.com/openqasm/openpulse-python/blob/main/source/grammar/openpulseLexer.g4). Only words from below sections are picked as it is more likely that user might use such names.
- Language keywords
- Types
- Builtin identifiers and operations
Unit test has been added.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're …

fix: Error when FreeParameters are named QASM types

---

.github/dependabot.yml
src/braket/circuits/duration_gate.py
src/braket/circuits/gate.py
src/braket/circuits/gates.py
src/braket/circuits/text_diagram_builders/unicode_circuit_diagram.py
test/unit_tests/braket/circuits/test_ascii_circuit_diagram.py
test/unit_tests/braket/circuits/test_duration_gate.py
test/unit_tests/braket/circuits/test_gates.py
test/unit_tests/braket/circuits/test_unicode_circuit_diagram.py

Fixes https://github.com/amazon-braket/amazon-braket-sdk-python/issues/974
- Unit test coverage is 100%.
- Running this code produces this QASM code
```python
from braket.circuits import Circuit
circ = Circuit().barrier([0, 1, 2])
print(circ.to_ir("OPENQASM").source)
```
```text
OPENQASM 3.0;
bit[3] b;
qubit[3] q;
barrier q[0], q[1], q[2];
b[0] = measure q[0];
b[1] = measure q[1];
b[2] = measure q[2];
```
```python
from braket.circuits import Circuit
circ = Circuit().delay([0, 1, 2], 30)
print(circ.to_ir("OPENQASM").source)
```
```text
OPENQASM 3.0;
bit[3] b;
qubit[3] q;
delay[30 s] q[0], q[1], q[2];
b[0] = measure q[0];
b[1] = measure q[1];
b[2] = measure q[2];
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, …

feature: Add delay and barrier for circuits

---

.github/pull_request_template.md
CONTRIBUTING.md

Instructions about commit messages should really refer to PR titles, since that's what ends up in the commit log.
Note - after getting approval and merging this, I'll make the same change in the several other Braket repos which contain this content in their CONTRIBUTING.md.

doc: update PR title instructions

---

src/braket/devices/devices.py
test/integ_tests/test_device_creation.py
test/integ_tests/test_measure.py

deprecation: Remove OQC

---

examples/bell_result_types.py
examples/hybrid_job.py
examples/hybrid_job_script.py
examples/local_noise_simulation.py
src/braket/circuits/observable.py
src/braket/circuits/observables.py
src/braket/circuits/result_types.py
test/unit_tests/braket/circuits/test_observables.py

Allows observables to be constructed with target qubits:
```python
obs = X(0) @ Z(2)
```
and as a side effect result types to be constructed without targets:
```python
circ.expectation(obs)
```

feat: Allow early qubit binding of observables

---

src/braket/pulse/waveforms.py
test/unit_tests/braket/pulse/ast/test_approximation_parser.py
test/unit_tests/braket/pulse/test_pulse_sequence.py
test/unit_tests/braket/pulse/test_waveforms.py

Add an `off_center` parameter to allow offsetting the smoothed square toward left or right in a erf_square waveform.
tox

feat: add off_center to erf_square

---

src/braket/circuits/result_type.py
src/braket/circuits/result_types.py
test/unit_tests/braket/circuits/test_result_types.py

fix: Use observable targets for targetless results

---

src/braket/circuits/circuit.py
src/braket/circuits/observable.py
src/braket/circuits/observables.py
src/braket/circuits/result_type.py
src/braket/circuits/result_types.py
test/unit_tests/braket/circuits/test_result_type.py

Also changed `Observable` to teturn `QubitSet` for absent observable target

change: Return observable target if absent for RT

---

src/braket/devices/local_simulator.py
test/unit_tests/braket/devices/test_local_simulator.py

Properly pass through `inputs` when simulating a `SerializableProgram` instance.
`tox` passes.

fix: Pass through inputs for SerializableProgram simulation

---

.coveragerc
src/braket/aws/aws_quantum_task_batch.py

Corrects the return type and docstring for these methods.

fix: correct typing for task results methods

---

src/braket/devices/devices.py
test/integ_tests/test_device_creation.py
test/integ_tests/test_measure.py
test/integ_tests/test_pulse.py

Also made integ tests more robust to device retirement

deprecation: Ankaa-2

---

src/braket/jobs/hybrid_job.py

Skip copying inner function source to decorator job when there is no inner function. The job interface did not handle empty input gracefully. 
tox

fix: decorator job with no inner function

---

src/braket/_sdk/_version.py
src/braket/aws/aws_quantum_task.py
test/unit_tests/braket/aws/test_aws_quantum_task.py

Prevent `AwsQuantumTask.__init__` from throwing an exception if additional `kwargs` are passed in. One downstream scenario this unblocks is in Qiskit-Braket provider, which passes through `kwargs` from the Qiskit layer, some of which may be unknown to the Braket SDK. (Specifically, when using the Braket backend for `EstimatorV2` in Qiskit, an unknown kwarg `seed_simulator` is passed - which blocks that use case. Thanks to @speller26 for debugging and flagging this.)
`tox` passes. Also verified the Braket backend from Qiskit-Braket provider works correctly when used with Qiskit's `EstimatorV2`.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …

fix: Update AwsQuantumTask.__init__ signature

---

src/braket/aws/aws_session.py
test/unit_tests/braket/aws/test_aws_session.py

A change in botocore v1.37.4 (https://github.com/boto/botocore/pull/3389) results in the Braket custom user agent strings being overwritten. This change sets the Braket custom user agent strings in the Boto3 config object, which prevents it from getting overwritten when Boto3 rebuilds its user agent string.
`tox`. Also verified that user agent integration tests, which were failing before this change, are now passing.
By submitting this pull request, I confirm that my …

fix: Set user agent in Boto3 config object

---

pyproject.toml

`ruff` has started failing on `main` with these errors:
```
src/braket/aws/aws_session.py:871:20: PLC0207 Accessing only the first or last element of `str.split()` without setting `maxsplit=1`
|
869 |             str: Verbose image tag for given image.
870 |         """
871 |         registry = image_uri.split(".")[0]
|                    ^^^^^^^^^^^^^^^^^^^^^^^ PLC0207
872 |         repository, tag = image_uri.split("/")[-1].split(":")
|
src/braket/aws/aws_session.py:872:27: PLC0207 Accessing only the first or last element of `str.split()` without setting `maxsplit=1`
|
870 |         """
871 |         registry = image_uri.split(".")[0]
872 |         repository, tag = image_uri.split("/")[-1].split(":")
|                           ^^^^^^^^^^^^^^^^^^^^^^^^ PLC0207 …
```

infra: ignore linter error PLC0207 to unblock CI

---

src/braket/circuits/angled_gate.py
src/braket/circuits/noise_model/noise_model.py
test/unit_tests/braket/circuits/noise/test_noise_model.py

Today, when a noise model with MeasureCriteria is applied to a circuit with ObservableResultType, we got an error
```
from braket.circuits import Circuit, Observable
from braket.circuits.noise_model import NoiseModel, MeasureCriteria
from braket.circuits.noises import BitFlip
noise_model = NoiseModel()
noise_model.add_noise(BitFlip(0.1), MeasureCriteria(qubits=[0]))
circ = Circuit().h(0).sample(observable=Observable.Z())
print(circ)
noisy_circuit = noise_model.apply(circ)
```
gives
```
T  : │  0  │Result Types │
┌───┐ ┌───────────┐ 
q0 : ─┤ H ├─┤ Sample(Z) ├─
└───┘ └───────────┘ 
T  : │  0  │Result Types │
...
AttributeError: 'MeasureCriteria' object has no attribute 'result_type_matches'
```
In the function …

fix:  Fix applying readout error with ObservableResultType and MeasureCriteria

---

src/braket/circuits/circuit.py
test/unit_tests/braket/circuits/test_circuit.py

`Circuit._map_target_qubits` is used to stored the measured qubits of the circuit. The stored measured qubits is incorrect if adding measure instruction with `target_mapping`.
tox

fix: caching measured qubits

---

src/braket/circuits/circuit.py
src/braket/circuits/compiler_directives.py
src/braket/circuits/moments.py
src/braket/circuits/text_diagram_builders/ascii_circuit_diagram.py
src/braket/circuits/text_diagram_builders/text_circuit_diagram_utils.py
src/braket/circuits/text_diagram_builders/unicode_circuit_diagram.py
test/unit_tests/braket/circuits/test_ascii_circuit_diagram.py
test/unit_tests/braket/circuits/test_circuit.py
test/unit_tests/braket/circuits/test_compiler_directives.py
test/unit_tests/braket/circuits/test_moments.py
test/unit_tests/braket/circuits/test_unicode_circuit_diagram.py

#974 
Starting with the changes from #993 and #1002, the `barrier` instruction is implemented as a `CompilerDirective`. To this end, changes were necessary in a few files.
`tox`

feature: add barrier instruction
